---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti sulla classificazione BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Queste FAQ possono essere utili se stai cercando una risposta rapida a una domanda.



== Servizio di classificazione BlueXP

Le seguenti domande forniscono una comprensione generale della classificazione BlueXP.



=== Come funziona la classificazione BlueXP?

La classificazione BlueXP  implementa un altro layer di ai insieme al tuo sistema BlueXP  e ai sistemi storage. Esegue quindi la scansione dei dati su volumi, bucket, database e altri account storage e indicizza le informazioni sui dati trovate. La classificazione BlueXP sfrutta sia l'intelligenza artificiale che l'elaborazione del linguaggio naturale, al contrario di soluzioni alternative che sono comunemente costruite intorno alle espressioni regolari e alla corrispondenza dei modelli.

La classificazione BlueXP utilizza l'ai per fornire una comprensione contestuale dei dati per un rilevamento e una classificazione accurati. È basato sull'ai perché è progettato per i moderni tipi di dati e la scalabilità. Inoltre, comprende il contesto dei dati per fornire un rilevamento e una classificazione efficaci e precisi.

link:concept-cloud-compliance.html["Scopri di più sul funzionamento della classificazione BlueXP"].



=== La classificazione BlueXP dispone di un'API REST e funziona con strumenti di terze parti?

Sì, la classificazione BlueXP  dispone di un'API REST per le funzionalità supportate nella versione di classificazione BlueXP  che fa parte della piattaforma BlueXP  core. Vedere link:api-classification.html["Documentazione API"].



=== La classificazione BlueXP  è disponibile attraverso i marketplace del cloud?

La classificazione BlueXP  fa parte delle funzionalità principali di BlueXP , pertanto non è necessario utilizzare i mercati per questo servizio .



== Analisi e scansione della classificazione BlueXP

Le seguenti domande si riferiscono alle prestazioni di scansione della classificazione BlueXP  e all'analisi.



=== Con quale frequenza la classificazione BlueXP esegue la scansione dei dati?

Mentre la scansione iniziale dei dati potrebbe richiedere un po' di tempo, le scansioni successive esaminano solo le modifiche incrementali, riducendo i tempi di scansione del sistema. La classificazione BlueXP scansiona continuamente i dati in modo round-robin, sei repository alla volta, in modo che tutti i dati modificati vengano classificati molto rapidamente.

link:task-scanning-overview.html["Scopri come funzionano le scansioni"].

La classificazione BlueXP  esegue la scansione dei database solo una volta al giorno; i database non vengono sottoposti a scansione continua come altre origini dati.

Le scansioni dei dati hanno un impatto trascurabile sui sistemi storage e sui dati.



=== Le prestazioni di scansione variano?

Le prestazioni di scansione possono variare in base alla larghezza di banda della rete e alle dimensioni medie dei file nell'ambiente in uso. Può anche dipendere dalle caratteristiche di dimensione del sistema host (nel cloud o on-premise). Per ulteriori informazioni, vedere link:concept-cloud-compliance.html["L'istanza di classificazione BlueXP"] e. link:task-deploy-overview.html["Implementazione della classificazione BlueXP"]

Quando si aggiungono inizialmente nuove origini dati, è anche possibile scegliere di eseguire solo una scansione di "mappatura" (solo mappatura) invece di una scansione di "classificazione" completa (mappa e classificazione). Il mapping può essere eseguito sulle origini dati molto rapidamente perché non accede ai file per vedere i dati all'interno. link:task-scanning-overview.html["Vedere la differenza tra una scansione di mappatura e di classificazione"].



=== Posso cercare i miei dati usando la classificazione BlueXP?

La classificazione BlueXP offre ampie funzionalità di ricerca che semplificano la ricerca di un file o di un dato specifico in tutte le origini connesse. La classificazione BlueXP consente agli utenti di effettuare ricerche più approfondite rispetto a quanto riflettono i metadati. Si tratta di un servizio indipendente dal linguaggio che può anche leggere i file e analizzare una moltitudine di tipi di dati sensibili, come nomi e ID. Ad esempio, gli utenti possono eseguire ricerche negli archivi di dati strutturati e non strutturati per trovare dati che potrebbero essere trapelati dai database ai file utente, in violazione delle policy aziendali. Le ricerche possono essere salvate in un secondo momento e le policy possono essere create per eseguire ricerche e azioni sui risultati a una frequenza impostata.

Una volta trovati i file di interesse, è possibile elencare le caratteristiche, inclusi tag, account dell'ambiente di lavoro, bucket, percorso file, categoria (dalla classificazione), dimensione del file, ultima modifica, stato delle autorizzazioni, duplicati, livello di sensibilità, dati personali, tipi di dati sensibili all'interno del file, proprietario, tipo di file, dimensione del file, tempo di creazione, hash di file, se i dati sono stati assegnati a qualcuno che cerca la loro attenzione, e altro ancora. I filtri possono essere applicati a caratteristiche non pertinenti.

La classificazione BlueXP  dispone inoltre di role-based access control (RBAC) per consentire lo spostamento o l'eliminazione dei file, se sono presenti le autorizzazioni giuste. Se non sono presenti le autorizzazioni corrette, è possibile assegnare le attività a un utente dell'organizzazione che dispone delle autorizzazioni appropriate.



== Gestione e privacy della classificazione BlueXP

Le seguenti domande forniscono informazioni su come gestire le impostazioni di classificazione e privacy di BlueXP.



=== Come si attiva o disattiva la classificazione BlueXP ?

Innanzitutto, è necessario implementare un'istanza della classificazione BlueXP in BlueXP o in un sistema on-premise. Una volta eseguita l'istanza, è possibile attivare il servizio su ambienti di lavoro, database e altre origini dati esistenti dalla scheda *Configurazione* o selezionando un ambiente di lavoro specifico. link:task-getting-started-compliance.html["Scopri come iniziare"].


NOTE: Attivando la classificazione BlueXP su un'origine dati si ottiene una scansione iniziale immediata. I risultati della scansione vengono visualizzati subito dopo.

Puoi disattivare la classificazione BlueXP dall'eseguire la scansione di un singolo ambiente di lavoro, database o gruppo di condivisioni di file dalla pagina di configurazione della classificazione BlueXP. Vedere link:task-managing-compliance.html["Rimuovere le origini dati dalla classificazione BlueXP"].

Per rimuovere completamente l'istanza di classificazione BlueXP, è possibile rimuovere manualmente l'istanza di classificazione BlueXP dal portale del provider di cloud o dalla posizione on-premise.



=== Il servizio può escludere la scansione dei dati in determinate directory?

Sì. Se si desidera che la classificazione BlueXP escluda la scansione dei dati che risiedono in determinate directory di origine dati, è possibile fornire tale elenco al motore di classificazione. Dopo aver applicato questa modifica, la classificazione BlueXP esclude la scansione dei dati nelle directory specificate. link:task-exclude-scan-paths.html["Scopri di più"].



=== Le snapshot che risiedono su volumi ONTAP vengono sottoposte a scansione?

No La classificazione BlueXP non scansiona gli snapshot perché il contenuto è identico al contenuto del volume.



=== Cosa succede se il tiering dei dati è attivato sui volumi ONTAP?

Quando la classificazione BlueXP  esegue la scansione di volumi con dati cold a livello nell'archiviazione a oggetti utilizzando solo la mappatura, esegue la scansione di tutti i dati presenti sui dischi locali e dei dati cold a livello nell'archiviazione a oggetti. Ciò vale anche per i prodotti non NetApp che implementano il tiering.

La scansione solo mappatura non riscalda i dati freddi: Rimane fredda e rimane nello storage a oggetti. D'altra parte, se si esegue la scansione Map & Classify, alcune configurazioni potrebbero riscaldare i dati cold.



== Tipi di sistemi di origine e tipi di dati

Le domande seguenti riguardano i tipi di storage che è possibile sottoporre a scansione e i tipi di dati sottoposti a scansione.



=== Esistono restrizioni quando viene implementato in un'area governativa?

La classificazione BlueXP è supportata quando il connettore viene implementato in un'area governativa (AWS GovCloud, Azure Gov o Azure DoD), nota anche come "modalità limitata".



=== Quali origini dati è possibile eseguire la scansione se si installa la classificazione BlueXP in un sito senza accesso a Internet?

La classificazione BlueXP può eseguire la scansione dei dati solo da origini dati locali al sito on-premise. Al momento, la classificazione BlueXP può eseguire la scansione delle seguenti origini dati locali in "modalità privata", nota anche come sito "scuro":

* Sistemi ONTAP on-premise
* Schemi di database
* Storage a oggetti che utilizza il protocollo S3 (Simple Storage Service)


Vedere link:concept-cloud-compliance.html["Ambienti di lavoro e origini dati supportati"].



=== Quali tipi di file sono supportati?

La classificazione BlueXP esegue la scansione di tutti i file per informazioni su categorie e metadati e visualizza tutti i tipi di file nella sezione tipi di file della dashboard.

Quando la classificazione BlueXP rileva le informazioni personali identificabili (PII) o quando esegue una ricerca DSAR, sono supportati solo i seguenti formati di file:

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== Quali tipi di dati e metadati cattura la classificazione BlueXP?

La classificazione BlueXP consente di eseguire una scansione generale di "mappatura" o una scansione completa di "classificazione" sulle origini dati. La mappatura fornisce solo una panoramica di alto livello dei dati, mentre la classificazione fornisce una scansione di alto livello dei dati. Il mapping può essere eseguito sulle origini dati molto rapidamente perché non accede ai file per vedere i dati all'interno.

* *Scansione mappatura dati (solo scansione mappatura)*: La classificazione BlueXP  esegue la scansione solo dei metadati. Questo è utile per la gestione e la governance dei dati globali, l'ambito rapido dei progetti, le proprietà molto grandi e la prioritizzazione. La mappatura dei dati si basa sui metadati ed è considerata una scansione *rapida*.
+
Dopo una scansione rapida, è possibile generare un report di mappatura dei dati. Questo report offre una panoramica dei dati memorizzati nelle origini dati aziendali per aiutarti a prendere decisioni in merito all'utilizzo delle risorse, alla migrazione, al backup, alla sicurezza e ai processi di conformità.

* *Classificazione dei dati scansione profonda (scansione mappa e classificazione)*: Scansioni di classificazione BlueXP  utilizzando protocolli standard e autorizzazioni di sola lettura in tutti gli ambienti. I file selezionati vengono aperti e sottoposti a scansione per rilevare dati aziendali sensibili, informazioni private e problemi relativi al ransomware.
+
Dopo una scansione completa, sono disponibili molte funzionalità di classificazione BlueXP aggiuntive che è possibile applicare ai dati, ad esempio visualizzare e perfezionare i dati nella pagina Data Investigation, cercare i nomi all'interno dei file, copiare, spostare ed eliminare i file di origine e molto altro ancora.



La classificazione BlueXP acquisisce metadati come nome del file, autorizzazioni, ora di creazione, ultimo accesso e ultima modifica. Sono inclusi tutti i metadati visualizzati nella pagina Data Investigatcdion Details e nei Data Investigatcdion Reports.

La classificazione BlueXP  è in grado di identificare molti tipi di dati privati, come le informazioni personali (PII) e le informazioni personali sensibili (SPII). Per ulteriori informazioni sui dati privati, fare riferimento alla sezione https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Categorie di dati privati analizzate dalla classificazione BlueXP"].



=== Posso limitare le informazioni di classificazione di BlueXP a utenti specifici?

Sì, la classificazione BlueXP è completamente integrata con BlueXP. Gli utenti BlueXP  possono visualizzare solo le informazioni relative agli ambienti di lavoro che possono visualizzare in base alle loro autorizzazioni.

Inoltre, se si desidera consentire a determinati utenti di visualizzare solo i risultati della scansione di classificazione BlueXP  senza la possibilità di gestire le impostazioni di classificazione BlueXP , è possibile assegnare a tali utenti il ruolo *visualizzatore di classificazione* (quando si utilizza BlueXP  in modalità standard) o il ruolo *Visualizzatore di conformità* (quando si utilizza BlueXP  in modalità limitata). link:concept-cloud-compliance.html["Scopri di più"].



=== Qualcuno può accedere ai dati privati inviati tra il browser e la classificazione BlueXP?

No I dati privati inviati tra il browser e l'istanza di classificazione BlueXP sono protetti con una crittografia end-to-end che utilizza TLS 1,2, il che significa che NetApp e terze parti non possono leggerli. La classificazione BlueXP non condividerà dati o risultati con NetApp a meno che non venga richiesto e approvato l'accesso.

I dati sottoposti a scansione rimangono nell'ambiente in cui si opera.



=== Come vengono gestiti i dati sensibili?

NetApp non ha accesso ai dati riservati e non li visualizza nell'interfaccia utente. I dati sensibili vengono mascherati, ad esempio gli ultimi quattro numeri vengono visualizzati per le informazioni sulla carta di credito.



=== Dove sono memorizzati i dati?

I risultati della scansione sono memorizzati in Elasticsearch all'interno dell'istanza di classificazione BlueXP.



=== Come si accede ai dati?

La classificazione BlueXP accede ai dati archiviati in Elasticsearch tramite chiamate API, che richiedono autenticazione e sono crittografati tramite AES-128. L'accesso a Elasticsearch richiede direttamente l'accesso root.



== Licenze e costi

La seguente domanda riguarda le licenze e i costi per l'utilizzo della classificazione BlueXP.



=== Quanto costa la classificazione BlueXP?

La classificazione BlueXP è una funzionalità chiave di BlueXP e non è addebitata



== Implementazione del connettore

Le seguenti domande si riferiscono a BlueXP Connector.



=== Che cos'è il connettore?

Il connettore è un software in esecuzione su un'istanza di calcolo all'interno del tuo account cloud o on-premise, che consente a BlueXP di gestire in modo sicuro le risorse cloud. È necessario implementare un connettore per utilizzare la classificazione BlueXP.



=== Dove deve essere installato il connettore?

Durante la scansione dei dati, il connettore BlueXP  deve essere installato nelle seguenti posizioni:

* Per Cloud Volumes ONTAP in AWS o Amazon FSX per ONTAP: Connector è in AWS.
* Per Cloud Volumes ONTAP in Azure o in Azure NetApp Files: Il connettore si trova in Azure.
* Per Cloud Volumes ONTAP in GCP: Il connettore è in GCP.
* Per i sistemi ONTAP on-premise: Il connettore è on-premise.


Se si dispone di dati in queste posizioni, potrebbe essere necessario utilizzare https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["Connettori multipli"^].



=== La classificazione BlueXP richiede l'accesso alle credenziali?

La classificazione BlueXP non recupera le credenziali di storage. Al contrario, vengono archiviati nel connettore BlueXP.

La classificazione BlueXP usa le credenziali del piano dati, ad esempio, le credenziali CIFS per montare le condivisioni prima della scansione.



=== La comunicazione tra il servizio e il connettore utilizza il protocollo HTTP?

Sì, la classificazione BlueXP comunica con il connettore BlueXP tramite HTTP.



== Implementazione della classificazione BlueXP

Le seguenti domande si riferiscono all'istanza di classificazione BlueXP separata.



=== Quali modelli di implementazione supporta la classificazione BlueXP?

BlueXP consente all'utente di eseguire scansioni e report sui sistemi praticamente ovunque, inclusi ambienti on-premise, cloud e ibridi. La classificazione BlueXP viene normalmente implementata utilizzando un modello SaaS, in cui il servizio viene attivato tramite l'interfaccia BlueXP e non richiede alcuna installazione hardware o software. Anche in questa modalità di implementazione click-and-run, la gestione dei dati può essere eseguita indipendentemente dal fatto che gli archivi di dati siano on-premise o nel cloud pubblico.



=== Quale tipo di istanza o macchina virtuale è richiesto per la classificazione BlueXP?

Quando link:task-deploy-cloud-compliance.html["implementato nel cloud"]:

* In AWS, la classificazione BlueXP viene eseguita su un'istanza m6i.4xlarge con un disco GP2 da 500 GiB. È possibile selezionare un tipo di istanza più piccolo durante la distribuzione.
* In Azure, la classificazione BlueXP viene eseguita su una macchina virtuale Standard_D16s_v3 con un disco da 500 GiB.
* In GCP, la classificazione BlueXP viene eseguita su una macchina virtuale n2-standard-16 con un disco persistente 500 GiB Standard.


link:concept-cloud-compliance.html["Scopri di più sul funzionamento della classificazione BlueXP"].



=== È possibile implementare la classificazione BlueXP sul proprio host?

Sì. È possibile installare il software di classificazione BlueXP su un host Linux con accesso a Internet nella rete o nel cloud. Tutto funziona allo stesso modo e si continua a gestire la configurazione e i risultati della scansione tramite BlueXP. Vedere link:task-deploy-compliance-onprem.html["Implementazione della classificazione BlueXP on-premise"] per i requisiti di sistema e i dettagli sull'installazione.



=== E i siti sicuri senza accesso a Internet?

Sì, anche questo è supportato. È possibile link:task-deploy-compliance-dark-site.html["Implementare la classificazione BlueXP in un sito on-premise che non dispone di accesso a Internet"] per siti completamente sicuri.
