---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di classificazione BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/reference-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sulla classificazione BlueXP
      url: "/concept-cloud-compliance.html"
    - title: Implementare la classificazione BlueXP
      entries:
      - title: Quale distribuzione utilizzare
        url: "/task-deploy-overview.html"
      - title: Implementazione nel cloud con BlueXP
        url: "/task-deploy-cloud-compliance.html"
      - title: Installazione su un host Linux con accesso a Internet
        url: "/task-deploy-compliance-onprem.html"
      - title: Installazione su un host Linux on-premise senza accesso a Internet
        url: "/task-deploy-compliance-dark-site.html"
      - title: Verificare che l'host Linux sia pronto per installare la classificazione
          BlueXP
        url: "/task-test-linux-system.html"
    - title: Attivare la scansione sulle origini dati
      entries:
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX per ONTAP
        url: "/task-scanning-fsx.html"
      - title: Cloud Volumes ONTAP e ONTAP on-premise
        url: "/task-getting-started-compliance.html"
      - title: Schemi di database
        url: "/task-scanning-databases.html"
      - title: Condivisioni di file
        url: "/task-scanning-file-shares.html"
      - title: StorageGRID
        url: "/task-scanning-storagegrid.html"
    - title: Integrare Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: FAQ
      url: "/faq-cloud-compliance.html"
  - title: Utilizzare la classificazione BlueXP
    entries:
    - title: Visualizza i dettagli di governance relativi ai tuoi dati
      url: "/task-controlling-governance-data.html"
    - title: Visualizza i dettagli di conformità relativi ai tuoi dati
      url: "/task-controlling-private-data.html"
    - title: Categorie di dati privati
      url: "/reference-private-data-categories.html"
    - title: Analizzare i dati
      url: "/task-investigate-data.html"
    - title: Assegnare policy ai dati
      url: "/task-using-policies.html"
    - title: Modificare le impostazioni di scansione
      url: task-managing-repo-scanning.html
    - title: Generare report sulla conformità
      url: "/task-generating-compliance-reports.html"
  - title: Gestire la classificazione BlueXP
    entries:
    - title: Escludere le directory dalla scansione
      url: "/task-exclude-scan-paths.html"
    - title: Definire gli ID di gruppo esistenti come "aperti all'organizzazione"
      url: "/task-add-group-id-as-open.html"
    - title: Rimuovere le origini dati dalla classificazione BlueXP
      url: "/task-managing-compliance.html"
    - title: Disinstallare la classificazione BlueXP
      url: "/task-uninstall-data-sense.html"
  - title: Funzioni obsolete
    entries:
    - title: Elenco delle funzioni obsolete
      url: "/reference-free-paid.html"
    - title: Implementa le deprecazioni di classificazione BlueXP
      entries:
      - title: Installare la classificazione BlueXP su host multipli senza accesso
          a Internet
        url: "/task-deploy-multi-host-install-dark-site.html"
    - title: Deprecazioni dei dati di scansione
      entries:
      - title: Esegui la scansione dei bucket Amazon S3
        url: "/task-scanning-s3.html"
      - title: Eseguire la scansione degli account OneDrive
        url: "/task-scanning-onedrive.html"
      - title: Eseguire la scansione degli account SharePoint
        url: "/task-scanning-sharepoint.html"
      - title: Eseguire la scansione degli account Google Drive
        url: "/task-scanning-google-drive.html"
      - title: Scansione dello storage a oggetti che utilizza il protocollo S3
        url: "/task-scanning-object-storage.html"
    - title: Gestire le deprecazioni dei dati
      entries:
      - title: Visualizza i dettagli di governance sui dati nel dashboard Governance
        url: "/task-controlling-governance-dashboard-deprecated.html"
      - title: Organizzare i dati privati
        url: "/task-org-private-data.html"
      - title: Gestisci i tuoi dati privati
        url: "/task-managing-highlights.html"
      - title: Aggiungere identificatori di dati personali personalizzati
        url: "/task-managing-data-fusion.html"
      - title: Visualizzare lo stato delle azioni di classificazione di BlueXP
        url: "/task-view-compliance-actions.html"
      - title: Controllare la cronologia delle azioni di classificazione di BlueXP
        url: "/task-audit-data-sense-actions.html"
      - title: Ridurre la velocità di scansione della classificazione BlueXP
        url: "/task-reduce-scan-speed.html"
      - title: Rimuovere un account OneDrive, SharePoint o Google Drive
        url: "/task-managing-compliance-deprecated.html"
  - title: Riferimento
    entries:
    - title: Tipi di istanze di classificazione BlueXP supportati
      url: "/reference-instance-types.html"
    - title: Metadati raccolti dalle origini dati
      url: "/reference-collected-metadata.html"
    - title: Accedi al sistema di classificazione BlueXP
      url: "/reference-log-in-to-instance.html"
    - title: API di classificazione BlueXP
      url: "/api-classification.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
