---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, bluexp, scan shares 
summary: Le limitazioni note identificano le funzioni che non sono supportate da questa versione del prodotto o che non interagiscono correttamente con essa. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note nella classificazione BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano funzioni che non sono supportate o non interagiscono correttamente in questa versione. Esaminare attentamente queste limitazioni.



== Opzioni disabilitate per la classificazione BlueXP

La versione di dicembre 2023 (versione 1.26.6) ha rimosso le seguenti opzioni:

* L'opzione per attivare la raccolta del registro di controllo è stata disattivata.
* Durante l'indagine sulle directory, l'opzione per calcolare il numero di dati di informazioni personali identificabili (PII) da parte delle directory non è disponibile.
* L'opzione per integrare i dati utilizzando le etichette AIP (Azure Information Protection) è stata disattivata.




== Scansione della classificazione BlueXP

Le scansioni delle classificazioni BlueXP presentano le seguenti limitazioni.



=== La classificazione BlueXP esegue la scansione di una sola condivisione in un volume

Se si dispone di più condivisioni di file in un singolo volume, la classificazione BlueXP esegue la scansione della condivisione con la gerarchia più alta. Ad esempio, se si dispone di condivisioni come le seguenti:

* /A
* /A/B.
* /C.
* /D/E.


In questa configurazione, vengono scansionati solo i dati in /A. I dati in /C e /D non vengono scansionati.

.Soluzione alternativa
Esiste una soluzione per assicurarsi di eseguire la scansione dei dati da tutte le condivisioni del volume. Attenersi alla seguente procedura:

. Nell'ambiente di lavoro, aggiungere il volume da sottoporre a scansione.
. Dopo che la classificazione BlueXP ha completato la scansione del volume, accedere alla pagina _Data Investigation_ e creare un filtro per vedere quale condivisione viene sottoposta a scansione:
+
Filtra i dati in base a "Nome dell'ambiente di lavoro" e "Tipo di directory = Condivisione" per vedere quale condivisione viene scansionata.

. Ottenere l'elenco completo delle condivisioni presenti nel volume in modo da visualizzare le condivisioni non sottoposte a scansione.
. link:task-scanning-file-shares.html["Aggiungere le condivisioni rimanenti a un gruppo di condivisione"].
+
Aggiungi tutte le azioni singolarmente, ad esempio:

+
....
/C
/D
....
. Eseguire questa procedura per ogni volume dell'ambiente di lavoro che dispone di più condivisioni.




=== Ultimo timestamp di accesso

Quando la classificazione BlueXP esegue una scansione di una directory, la scansione influisce sul campo **Ultimo accesso** della directory. Quando si visualizza il campo **Ultimo accesso**, i metadati riflettono la data e l'ora della scansione o l'ultimo accesso dell'utente alla directory.
