---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Esistono molti tipi di dati privati che la classificazione BlueXP può identificare nei volumi, nei bucket Amazon S3, nei database, nelle cartelle OneDrive, negli account SharePoint, E Google Drive. 
---
= Categorie di dati privati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono molti tipi di dati privati che la classificazione BlueXP può identificare nei volumi e nei database.

La classificazione BlueXP identifica due tipi di dati personali:

* *Informazioni di identificazione personale (PII)*
* *Dati personali sensibili (SPii)*



TIP: Se è necessaria la classificazione BlueXP  per identificare altri tipi di dati privati, ad esempio numeri ID nazionali aggiuntivi o identificativi sanitari, contattare il proprio account manager.



== Tipi di dati personali

I dati personali, o _informazioni di identificazione personale_ (PII), contenuti nei file possono essere dati personali generici o identificatori nazionali. La terza colonna nella tabella seguente indica se la classificazione BlueXP utilizza link:task-controlling-private-data.html#view-files-that-contain-personal-data["convalida della prossimità"^] per convalidare i risultati per l'identificatore.

Le lingue in cui questi elementi possono essere riconosciuti sono identificate nella tabella.

[cols="13,37,10,8,8,8,8,8"]
|===
| Tipo | Identificatore | Convalida della prossimità? | Inglese | Tedesco | Spagnolo | Francese | Giapponese 


.6+| Generale | Numero della carta di credito | No | ✓ | ✓ | ✓ |  | ✓ 


| Soggetti dei dati | No | ✓ | ✓ | ✓ |  |  


| Indirizzo e-mail | No | ✓ | ✓ | ✓ |  | ✓ 


| Numero IBAN (International Bank account Number) | No | ✓ | ✓ | ✓ |  | ✓ 


| Indirizzo IP | No | ✓ | ✓ | ✓ |  | ✓ 


| Password | Sì | ✓ | ✓ | ✓ |  | ✓ 


.57+| Identificatori nazionali | TFN australiano (Tax file Number) | Sì | ✓ | ✓ | ✓ |  |  


| Patente di guida australiana | Sì | ✓ | ✓ | ✓ |  |  


| Numero di assistenza medica australiana | Sì | ✓ | ✓ | ✓ |  |  


| Australian Passport Number (numero passaporto australiano) | Sì | ✓ | ✓ | ✓ |  |  


| SSN austriaco | Sì | ✓ | ✓ | ✓ |  |  


| ID belga (numero nazionale) | Sì | ✓ | ✓ | ✓ |  |  


| Numero della carta d'identità del Botswana (Omang) | Sì | ✓ | ✓ | ✓ |  |  


| Numero passaporto Botswana | Sì | ✓ | ✓ | ✓ |  |  


| ID brasiliano (CPF) | Sì | ✓ | ✓ | ✓ |  |  


| British Passport | Sì | ✓ | ✓ | ✓ |  |  


| ID bulgaro (UCN) | Sì | ✓ | ✓ | ✓ |  |  


| ID croato (OIB) | Sì | ✓ | ✓ | ✓ |  |  


| Codice fiscale di Cipro (TIC) | Sì | ✓ | ✓ | ✓ |  |  


| Documento d'identità ceco/slovacco | Sì | ✓ | ✓ | ✓ |  |  


| ID danese (CPR) | Sì | ✓ | ✓ | ✓ |  |  


| Olandese ID (BSN) | Sì | ✓ | ✓ | ✓ |  |  


| ID estone | Sì | ✓ | ✓ | ✓ |  |  


| ID finlandese (HETU) | Sì | ✓ | ✓ | ✓ |  |  


| Patente di guida francese | Sì | ✓ | ✓ | ✓ | ✓ |  


| ID francese | Sì | ✓ | ✓ | ✓ | ✓ |  


| Francese INSEE | Sì | ✓ | ✓ | ✓ | ✓ |  


| Numero di previdenza sociale francese | Sì | ✓ | ✓ | ✓ | ✓ |  


| Francese Tax Identification Number (SPI) | Sì | ✓ | ✓ | ✓ | ✓ |  


| ID tedesco (Personalausweisnummer) | Sì | ✓ | ✓ | ✓ |  |  


| Tedesco ID interno per bonifici bancari | Sì | ✓ | ✓ | ✓ |  |  


| Numero tedesco di previdenza sociale (Sozialversicherungsnummer) | Sì | ✓ | ✓ | ✓ |  |  


| Codice fiscale tedesco (Steuerliche Identifikationsnummer) | Sì | ✓ | ✓ | ✓ |  |  


| ID greco | Sì | ✓ | ✓ | ✓ |  |  


| Codice fiscale ungherese | Sì | ✓ | ✓ | ✓ |  |  


| Irish ID (PPS) (ID irlandese) | Sì | ✓ | ✓ | ✓ |  |  


| ID Israeliano | Sì | ✓ | ✓ | ✓ |  |  


| Codice fiscale italiano | Sì | ✓ | ✓ | ✓ |  |  


| Codice di identificazione personale giapponese (personale e aziendale) | Sì | ✓ | ✓ | ✓ |  | ✓ 


| Documento d'identità lettone | Sì | ✓ | ✓ | ✓ |  |  


| ID lituano | Sì | ✓ | ✓ | ✓ |  |  


| Lussemburgo ID | Sì | ✓ | ✓ | ✓ |  |  


| ID maltese | Sì | ✓ | ✓ | ✓ |  |  


| Numero NHS (National Health Service) | Sì | ✓ | ✓ | ✓ |  |  


| Conto bancario della Nuova Zelanda | Sì | ✓ | ✓ | ✓ |  |  


| Patente di guida della Nuova Zelanda | Sì | ✓ | ✓ | ✓ |  |  


| Numero IRD Nuova Zelanda (ID fiscale) | Sì | ✓ | ✓ | ✓ |  |  


| New Zealand NHI (National Health Index) | Sì | ✓ | ✓ | ✓ |  |  


| Numero di passaporto per la Nuova Zelanda | Sì | ✓ | ✓ | ✓ |  |  


| ID polacco (PESEL) | Sì | ✓ | ✓ | ✓ |  |  


| Portoghese Tax Identification Number (NIF) | Sì | ✓ | ✓ | ✓ |  |  


| ID rumeno (CNP) | Sì | ✓ | ✓ | ✓ |  |  


| Singapore National Registration Identity Card (NRIC) | Sì | ✓ | ✓ | ✓ |  |  


| ID sloveno (EMSO) | Sì | ✓ | ✓ | ✓ |  |  


| ID sudafricano | Sì | ✓ | ✓ | ✓ |  |  


| Codice fiscale spagnolo | Sì | ✓ | ✓ | ✓ |  |  


| ID svedese | Sì | ✓ | ✓ | ✓ |  |  


| Texas driver's License | Sì | ✓ | ✓ | ✓ |  |  


| REGNO UNITO ID (NINO) | Sì | ✓ | ✓ | ✓ |  |  


| USA California driver's License | Sì | ✓ | ✓ | ✓ |  |  


| USA, Indiana driver's License | Sì | ✓ | ✓ | ✓ |  |  


| USA New York driver's License | Sì | ✓ | ✓ | ✓ |  |  


| Numero di previdenza sociale (SSN) USA | Sì | ✓ | ✓ | ✓ |  |  
|===


== Tipi di dati personali sensibili

La classificazione BlueXP può trovare nei file le seguenti informazioni personali sensibili (SPii).

Al momento, gli elementi di questa categoria possono essere riconosciuti solo in inglese.

* *Procedura penale riferimento*: Dati relativi alle condanne penali e ai reati di una persona fisica.
* *Riferimento etnico*: Dati relativi all'origine razziale o etnica di una persona fisica.
* *Health Reference*: Dati relativi alla salute di una persona fisica.
* *ICD-9-CM codici medici*: Codici utilizzati nell'industria medica e sanitaria.
* *ICD-10-CM codici medici*: Codici utilizzati nell'industria medica e sanitaria.
* *Principi filosofici riferimento*: Dati riguardanti le credenze filosofiche di una persona fisica.
* *Pareri politici riferimento*: Dati relativi alle opinioni politiche di una persona fisica.
* *Religious credences Reference*: Dati relativi alle credenze religiose di una persona fisica.
* *Sex Life o Orientation Reference*: Dati relativi alla vita sessuale o all'orientamento sessuale di una persona fisica.




== Tipi di categorie

La classificazione BlueXP classifica i tuoi dati nel modo seguente.

La maggior parte di queste categorie può essere riconosciuta in inglese, tedesco e spagnolo.

[cols="25,25,15,15,15"]
|===
| Categoria | Tipo | Inglese | Tedesco | Spagnolo 


.4+| Finanza | Bilanci | ✓ | ✓ | ✓ 


| Ordini di acquisto | ✓ | ✓ | ✓ 


| Fatture | ✓ | ✓ | ✓ 


| Report trimestrali | ✓ | ✓ | ✓ 


.6+| FC | Controlli in background | ✓ |  | ✓ 


| Piani di compensazione | ✓ | ✓ | ✓ 


| Contratti con i dipendenti | ✓ |  | ✓ 


| Recensioni dei dipendenti | ✓ |  | ✓ 


| Salute | ✓ |  | ✓ 


| Riprende | ✓ | ✓ | ✓ 


.2+| Legale | NDA | ✓ | ✓ | ✓ 


| Contratti fornitore-cliente | ✓ | ✓ | ✓ 


.2+| Marketing | Campagne | ✓ | ✓ | ✓ 


| Conferenze | ✓ | ✓ | ✓ 


| Operazioni | Report di audit | ✓ | ✓ | ✓ 


| Vendite | Ordini di vendita | ✓ | ✓ |  


.4+| Servizi | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| SOW | ✓ | ✓ | ✓ 


| Formazione | ✓ | ✓ | ✓ 


| Supporto | Reclami e biglietti | ✓ | ✓ | ✓ 
|===
I seguenti metadati sono anche classificati e identificati nelle stesse lingue supportate:

* Dati dell'applicazione
* Archiviare i file
* Audio
* Breadcrumb dalla classificazione BlueXP
Dati delle applicazioni di business
* File CAD
* Codice
* Corrotto
* Database e file di indice
* File di progettazione
* Email Application Data (dati applicazione email)
* Crittografato (file con un elevato punteggio di entropia)
* Eseguibili
* Dati delle applicazioni finanziarie
* Health Application Data
* Immagini
* Registri
* Documenti vari
* Presentazioni varie
* Fogli di calcolo vari
* Varie "Sconosciuto"
* File protetti da password
* Dati strutturati
* Video
* File a byte zero




== Tipi di file

La classificazione BlueXP esegue la scansione di tutti i file per informazioni su categorie e metadati e visualizza tutti i tipi di file nella sezione tipi di file della dashboard.

Tuttavia, quando la classificazione BlueXP rileva le informazioni personali identificabili (PII) o quando esegue una ricerca DSAR, sono supportati solo i seguenti formati di file:

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



== Accuratezza delle informazioni rilevate

NetApp non può garantire la precisione del 100% dei dati personali e dei dati personali sensibili identificati dalla classificazione BlueXP. È sempre necessario convalidare le informazioni esaminando i dati.

In base ai nostri test, la tabella seguente mostra l'accuratezza delle informazioni rilevate dalla classificazione BlueXP. Lo suddivideremo per _precisione_ e _richiamo_:

Precisione:: La probabilità che la classificazione BlueXP trovi sia stata identificata correttamente. Ad esempio, un tasso di precisione del 90% per i dati personali significa che 9 file su 10 identificati come contenenti informazioni personali contengono effettivamente informazioni personali. 1 file su 10 sarebbe un falso positivo.
Ricorda:: Probabilità che la classificazione BlueXP trovi ciò che dovrebbe. Ad esempio, un tasso di richiamo del 70% per i dati personali significa che la classificazione BlueXP può identificare 7 file su 10 che contengono effettivamente informazioni personali nella tua organizzazione. La classificazione di BlueXP non consentirebbe il 30% dei dati e non verrà visualizzata nella dashboard.


Stiamo costantemente migliorando la precisione dei nostri risultati. Tali miglioramenti saranno automaticamente disponibili nelle future release di classificazione BlueXP.

[cols="25,20,20"]
|===
| Tipo | Precisione | Ricorda 


| Dati personali - Generale | 90%-95% | 60%-80% 


| Dati personali - identificatori del Paese | 30%-60% | 40%-60% 


| Dati personali sensibili | 80%-95% | 20%-30% 


| Categorie | 90%-97% | 60%-80% 
|===