---
sidebar: sidebar 
permalink: task-exclude-scan-paths.html 
keywords: exclude scans, folders, directories 
summary: Se si desidera che la classificazione BlueXP escluda la scansione dei dati che risiedono in determinate directory di origine dati, è possibile aggiungere questi nomi di directory a un file di configurazione. Dopo aver applicato questa modifica, il motore di classificazione BlueXP escluderà la scansione dei dati in tali directory. 
---
= Escludere directory specifiche dalle scansioni di classificazione BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si desidera che la classificazione BlueXP escluda la scansione dei dati che risiedono in determinate directory di origine dati, è possibile aggiungere questi nomi di directory a un file di configurazione. Dopo aver applicato questa modifica, il motore di classificazione BlueXP escluderà la scansione dei dati in tali directory.

La classificazione BlueXP è configurata per impostazione predefinita in modo da escludere la scansione dei dati snapshot del volume perché tale contenuto è identico al contenuto del volume.

Questa funzionalità è disponibile con la classificazione BlueXP versione 1,29 e successive (a partire da marzo 2024).



== Origini dati supportate

L'esclusione di directory specifiche dalle scansioni di classificazione BlueXP è supportata per le condivisioni NFS e CIFS nelle seguenti origini dati:

* ONTAP on-premise
* Cloud Volumes ONTAP
* Amazon FSX per NetApp ONTAP
* Azure NetApp Files
* Condivisioni di file generiche




== Definire le directory da escludere dalla scansione

Prima di poter escludere le directory dalla scansione della classificazione, è necessario accedere al sistema di classificazione BlueXP in modo da poter modificare un file di configurazione ed eseguire uno script. Scopri come link:reference-log-in-to-instance.html["Accedi al sistema di classificazione BlueXP"] A seconda che il software sia stato installato manualmente su una macchina Linux o se l'istanza è stata distribuita nel cloud.

[NOTE]
====
* È possibile escludere un massimo di 50 percorsi di directory per sistema di classificazione BlueXP.
* L'esclusione dei percorsi di directory può influire sui tempi di scansione.


====
.Fasi
. Nel sistema di classificazione BlueXP, vai a "/opt/netapp/config/custom_Configuration" e apri il file `data_provider.yaml`.
. Nella sezione "data_providers", sotto la riga "exclude:", immettere i percorsi di directory da escludere. Ad esempio:
+
....
exclude:
- "folder1"
- "folder2"
....
+
Non modificare altro contenuto in questo file.

. Salvare le modifiche apportate al file.
. Andare a "/opt/netapp/Datasense/tools/customer_Configuration/data_provider" ed eseguire il seguente script:
+
 update_data_providers_from_config_file.sh
+
Questo comando commette le directory da escludere dalla scansione al motore di classificazione.



.Risultato
Tutte le scansioni successive dei dati escluderanno la scansione di quelle directory specificate.

È possibile aggiungere, modificare o eliminare elementi dall'elenco Escludi utilizzando gli stessi passaggi. L'elenco di esclusione rivisto verrà aggiornato dopo l'esecuzione dello script per confermare le modifiche.



== Esempi

.Configurazione 1:
Ogni cartella che contiene "folder1" in qualsiasi punto del nome sarà esclusa da tutte le origini dati.

....
data_providers:
   exclude:
   - "folder1"
....
.Risultati previsti per i percorsi che saranno esclusi:
* /CVO1/folder1
* /CVO1/folder1name
* /CVO1/folder10
* /CVO1/*folder1
* /CVO1/+folder1name
* /CVO1/notfolder10
* /CVO22/folder1
* /CVO22/folder1name
* /CVO22/folder10


.Esempi di percorsi che non verranno esclusi:
* /CVO1/*cartella
* /CVO1/nome cartella
* /CVO22/*folder20


.Configurazione 2:
Ogni cartella che contiene "*folder1" solo all'inizio del nome sarà esclusa.

....
data_providers:
   exclude:
   - "\\*folder1"
....
.Risultati previsti per i percorsi che saranno esclusi:
* /CVO/*folder1
* /CVO/*folder1name
* /CVO/*folder10


.Esempi di percorsi che non verranno esclusi:
* /CVO/folder1
* /CVO/folder1name
* /CVO/NOT*folder10


.Configurazione 3:
Ogni cartella dell'origine dati "CVO22" che contiene "folder1" in qualsiasi punto del nome sarà esclusa.

....
data_providers:
   exclude:
   - "CVO22/folder1"
....
.Risultati previsti per i percorsi che saranno esclusi:
* /CVO22/folder1
* /CVO22/folder1name
* /CVO22/folder10


.Esempi di percorsi che non verranno esclusi:
* /CVO1/folder1
* /CVO1/folder1name
* /CVO1/folder10




== Escape di caratteri speciali nei nomi delle cartelle

Se si dispone di un nome di cartella che contiene uno dei seguenti caratteri speciali e si desidera escludere la scansione dei dati contenuti in tale cartella, sarà necessario utilizzare la sequenza di escape \\ prima del nome della cartella.

 ., +, *, ?, ^, $, (, ), [, ], {, }, |
Ad esempio:

Percorso in origine: `/project/*not_to_scan`

Sintassi nel file di esclusione: `"\\*not_to_scan"`



== Consente di visualizzare l'elenco di esclusione corrente

È possibile per i contenuti di `data_provider.yaml` il file di configurazione deve essere diverso da quello che è stato effettivamente eseguito dopo l'esecuzione di `update_data_providers_from_config_file.sh` script. Per visualizzare l'elenco corrente delle directory che hai escluso dalla scansione della classificazione BlueXP, esegui il seguente comando da "/opt/netapp/Datasense/tools/customer_Configuration/data_provider":

 get_data_providers_configuration.sh