---
sidebar: sidebar 
permalink: task-custom-classification.html 
keywords: custom classification, customize, regular expression, keyword, regex 
summary: 'La classificazione BlueXP  consente di personalizzare la ricerca di informazioni riservate, adattando il servizio a modelli e parole chiave specifici per l"organizzazione.' 
---
= Creare una classificazione personalizzata nella classificazione BlueXP 
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con la classificazione BlueXP , è possibile creare una ricerca personalizzata per le informazioni riservate. La ricerca può essere definita come ambito di un'espressione regolare o di una serie di parole chiave di prossimità.



== Creare una classificazione personalizzata

La classificazione personalizzata è disponibile solo per le scansioni Map & Classify, non solo per le scansioni mapping. Questa funzione è attualmente in anteprima.

.Fasi
. Selezionare la scheda **classificazione personalizzata**.
. Selezionare **Aggiungi nuovo classificatore**.
. Aggiungere Nome e Descrizione per il nuovo classificatore.
. Per aggiungere la personalizzazione come espressione regolare, selezionare **espressione regolare personalizzata** quindi **Avanti**.
+
.. Per un'espressione regolare, aggiungere il modello per rilevare le informazioni specifiche dei dati. Ad esempio, l'ID a 12 cifre che inizia con 201 è \B201\f\d(9)b. selezionare **convalida** per confermare la sintassi della voce.




La nuova personalizzazione viene acquisita nella successiva scansione pianificata. Per visualizzare i risultati, vedere xref:task-generating-compliance-reports.html[Generare report sulla conformità].
