---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Scopri le novità della classificazione BlueXP. 
---
= Novità della classificazione BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità della classificazione BlueXP.



== 17 luglio 2023 (versione 1.24)



=== Due nuovi tipi di dati personali tedeschi sono identificati dalla classificazione BlueXP

La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* ID tedesco (Personalausweisnummer)
* Numero tedesco di previdenza sociale (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].



=== Rocky Linux 9 è ora una distribuzione Linux supportata su cui è possibile installare la classificazione BlueXP

Rocky Linux 9 (9.0, 9.1 e 9.2) è stato qualificato come sistema operativo supportato per la classificazione BlueXP. È possibile installare la classificazione BlueXP su un host Rocky Linux nella rete o su un host Linux nel cloud quando si utilizza la versione 1.24 del programma di installazione. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Scopri come installare la classificazione BlueXP su un host con Rocky Linux installato"].



=== La classificazione BlueXP è completamente supportata in modalità limitata e privata

La classificazione BlueXP è ora completamente supportata nei siti senza accesso a Internet (modalità privata) e con accesso Internet in uscita limitato (modalità limitata). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri di più sulle modalità di implementazione di BlueXP per il connettore"^].



=== Possibilità di saltare le versioni durante l'aggiornamento di un'installazione in modalità privata della classificazione BlueXP

Ora è possibile eseguire l'aggiornamento a una versione più recente della classificazione BlueXP anche se non è sequenziale. Ciò significa che l'attuale limite di aggiornamento della classificazione BlueXP per una versione alla volta non è più necessario. Questa funzione è rilevante a partire dalla versione 1.24 in poi.



=== L'API di classificazione BlueXP è ora disponibile

L'API di classificazione BlueXP ti consente di eseguire azioni, creare query ed esportare informazioni sui dati che stai analizzando. La documentazione interattiva è disponibile utilizzando Swagger. La documentazione è suddivisa in più categorie, tra cui analisi, conformità, governance e configurazione. Ogni categoria è un riferimento alle schede nell'interfaccia utente di classificazione BlueXP.

Per accedere a Swagger, è necessario l'indirizzo IP dell'istanza di classificazione BlueXP. Nel caso di un'implementazione cloud, verrà utilizzato l'indirizzo IP pubblico. Quindi, è necessario accedere a questo endpoint:

https://<classification_ip>/documentation[]



== 6 giugno 2023 (versione 1.23)



=== Il giapponese è ora supportato durante la ricerca dei nomi dei soggetti dei dati

I nomi giapponesi possono ora essere inseriti quando si cerca il nome di un soggetto in risposta a una richiesta di accesso soggetto a dati (DSAR). È possibile generare un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["Report Data Subject Access Request"] con le informazioni risultanti. È inoltre possibile immettere i nomi giapponesi in https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["Filtro "Data Subject" nella pagina Data Investigation"] identificare i file che contengono il nome dell'oggetto.



=== Ubuntu è ora una distribuzione Linux supportata su cui è possibile installare la classificazione BlueXP

Ubuntu 22.04 è stato qualificato come sistema operativo supportato per la classificazione BlueXP. È possibile installare la classificazione BlueXP su un host Ubuntu Linux nella rete o su un host Linux nel cloud quando si utilizza la versione 1.23 del programma di installazione. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Scopri come installare la classificazione BlueXP su un host con Ubuntu installato"].



=== Red Hat Enterprise Linux 8.6 e 8.7 non sono più supportati con le nuove installazioni di classificazione BlueXP

Queste versioni non sono supportate con le nuove implementazioni perché Red Hat non supporta più Docker, che è un prerequisito. Se si dispone di una macchina di classificazione BlueXP esistente in esecuzione su RHEL 8.6 o 8.7, NetApp continuerà a supportare la configurazione.



=== La classificazione BlueXP può essere configurata come FPolicy Collector per ricevere eventi FPolicy dai sistemi ONTAP

È possibile consentire la raccolta dei registri di controllo dell'accesso ai file nel sistema di classificazione BlueXP per gli eventi di accesso ai file rilevati sui volumi negli ambienti di lavoro. La classificazione BlueXP può acquisire i seguenti tipi di eventi FPolicy e gli utenti che hanno eseguito le azioni sui file: Creare, leggere, scrivere, eliminare, rinominare, Modificare il proprietario/le autorizzazioni e modificare SACL/DACL. https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["Scopri come monitorare e gestire gli eventi di accesso ai file"].



=== Le licenze Data Sense BYOL sono ora supportate nei siti bui

Ora puoi caricare la tua licenza BYOL Data Sense nel portafoglio digitale BlueXP in un sito buio, in modo da ricevere una notifica quando la tua licenza sta per esaurirsi. https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["Scopri come ottenere e caricare la licenza BYOL Data Sense"].



== 3 aprile 2023 (versione 1.22)



=== Nuovo report sulla valutazione del rilevamento dei dati

Il Data Discovery Assessment Report fornisce un'analisi di alto livello dell'ambiente sottoposto a scansione per evidenziare i risultati del sistema e mostrare le aree problematiche e le potenziali fasi di risoluzione dei problemi. L'obiettivo di questo report è aumentare la consapevolezza dei problemi di governance dei dati, delle esposizioni alla sicurezza dei dati e delle lacune nella compliance dei dati del tuo set di dati. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["Scopri come generare e utilizzare il Data Discovery Assessment Report"].



=== Possibilità di implementare la classificazione BlueXP su istanze più piccole nel cloud

Quando si implementa la classificazione BlueXP da un connettore BlueXP in un ambiente AWS, è ora possibile scegliere tra due tipi di istanze più piccoli rispetto a quelli disponibili con l'istanza predefinita. Se si esegue la scansione di un ambiente di piccole dimensioni, questo può contribuire a risparmiare sui costi del cloud. Tuttavia, esistono alcune limitazioni quando si utilizza l'istanza più piccola. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Vedere i tipi di istanze e le limitazioni disponibili"].



=== È ora disponibile uno script standalone per qualificare il sistema Linux prima dell'installazione della classificazione BlueXP

Se si desidera verificare che il sistema Linux soddisfi tutti i prerequisiti indipendentemente dall'esecuzione dell'installazione di classificazione BlueXP, è possibile scaricare uno script separato che esegue solo i prerequisiti. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Scopri come verificare se il tuo host Linux è pronto per installare la classificazione BlueXP"].



== 7 marzo 2023 (versione 1.21)



=== Nuova funzionalità per aggiungere categorie personalizzate dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP consente ora di aggiungere le proprie categorie personalizzate in modo che la classificazione BlueXP identifichi i file che si adattano a tali categorie. La classificazione BlueXP è molto ampia https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["categorie predefinite"], pertanto, questa funzionalità consente di aggiungere categorie personalizzate per identificare dove si trovano informazioni specifiche per l'organizzazione nei dati.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["Scopri di più"^].



=== Ora è possibile aggiungere parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP ha avuto la possibilità di aggiungere parole chiave personalizzate che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare un'interfaccia a riga di comando per aggiungere le parole chiave. In questa release, la possibilità di aggiungere parole chiave personalizzate è nell'interfaccia utente di classificazione di BlueXP, rendendo molto semplice aggiungere e modificare queste parole chiave.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Scopri di più sull'aggiunta di parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP"^].



=== Possibilità di eseguire la classificazione BlueXP *non* dei file di scansione quando verrà modificato l'ultimo tempo di accesso

Per impostazione predefinita, se la classificazione di BlueXP non dispone di permessi di "scrittura" adeguati, il sistema non esegue la scansione dei file nei volumi perché la classificazione di BlueXP non può riportare l'ultimo tempo di accesso alla data e ora originale. Tuttavia, se non si ha alcun problema se l'ultimo tempo di accesso viene ripristinato all'ora originale nei file, è possibile ignorare questo comportamento nella pagina di configurazione in modo che la classificazione BlueXP scansiona i volumi indipendentemente dalle autorizzazioni.

In combinazione con questa funzionalità, è stato aggiunto un nuovo filtro denominato "Scan Analysis Event", che consente di visualizzare i file non classificati perché la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso o i file classificati anche se la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["Scopri di più su "Last Access Time timestamp" e sulle autorizzazioni richieste dalla classificazione BlueXP"].



=== Tre nuovi tipi di dati personali sono identificati dalla classificazione BlueXP

La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* Numero della carta d'identità del Botswana (Omang)
* Numero passaporto Botswana
* Singapore National Registration Identity Card (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].



=== Funzionalità aggiornate per le directory

* L'opzione "Light CSV Report" (Report CSV leggero) per i report di analisi dei dati include ora le informazioni provenienti dalle directory.
* Il filtro dell'ora "ultimo accesso" ora mostra l'ora dell'ultimo accesso per file e directory.




=== Miglioramenti all'installazione

* Il programma di installazione della classificazione BlueXP per i siti senza accesso a Internet (siti oscuri) ora esegue un controllo preliminare per assicurarsi che i requisiti di sistema e di rete siano stati soddisfatti per un'installazione corretta.
* I file di log di audit dell'installazione vengono salvati ora e scritti in `/ops/netapp/install_logs`.




== 5 febbraio 2023 (versione 1.20)



=== Possibilità di inviare e-mail di notifica basate su policy a qualsiasi indirizzo e-mail

Nelle versioni precedenti della classificazione BlueXP, è possibile inviare avvisi e-mail agli utenti BlueXP del proprio account quando alcuni criteri critici restituiscono risultati. Questa funzione ti consente di ricevere notifiche per proteggere i tuoi dati quando non sei online. Ora puoi anche inviare avvisi e-mail dalle policy a qualsiasi altro utente (fino a 20 indirizzi e-mail) che non sia presente nel tuo account BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["Scopri di più sull'invio di avvisi e-mail in base ai risultati della policy"].



=== Ora è possibile aggiungere modelli personali dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP ha avuto la possibilità di aggiungere "dati personali" personalizzati che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare una riga di comando per aggiungere i modelli personalizzati. In questa release, la possibilità di aggiungere modelli personali utilizzando un regex è nell'interfaccia utente di classificazione BlueXP, rendendo molto semplice aggiungere e modificare questi modelli personalizzati.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Scopri di più sull'aggiunta di modelli personalizzati dall'interfaccia utente di classificazione BlueXP"^].



=== Possibilità di spostare 15 milioni di file utilizzando la classificazione BlueXP

In passato era possibile che la classificazione BlueXP spostasse un massimo di 100,000 file di origine in qualsiasi condivisione NFS. Ora puoi spostare fino a 15 milioni di file alla volta. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Scopri di più sullo spostamento dei file di origine utilizzando la classificazione BlueXP"].



=== Possibilità di visualizzare il numero di utenti che hanno accesso ai file di SharePoint Online

Il filtro "numero di utenti con accesso" ora supporta i file memorizzati nei repository SharePoint Online. In passato erano supportati solo i file su condivisioni CIFS. Si noti che i gruppi SharePoint che non sono basati su Active Directory non verranno conteggiati in questo filtro al momento.



=== Il nuovo stato "Partial Success" (operazione riuscita parziale) è stato aggiunto al pannello Action Status (Stato azione)

Il nuovo stato "Partial Success" (successo parziale) indica che un'azione di classificazione BlueXP è terminata e che alcuni elementi hanno avuto esito negativo, ad esempio quando si spostano o si eliminano file 100. Inoltre, lo stato "Finished" (terminato) è stato rinominato "Success" (riuscito). In passato, lo stato "Finished" (terminato) potrebbe elencare le azioni riuscite e non riuscite. Ora lo stato "Success" significa che tutte le azioni sono riuscite su tutti gli elementi. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Vedere come visualizzare il pannello Actions Status (Stato azioni)"].



== 9 gennaio 2023 (versione 1.19)



=== Possibilità di visualizzare un grafico di file che contengono dati sensibili e che sono eccessivamente permissivi

La dashboard di governance ha aggiunto una nuova area _dati sensibili e permessi estesi_ che fornisce una mappa termica dei file che contengono dati sensibili (inclusi dati personali sensibili e sensibili) e che sono eccessivamente permissivi. In questo modo è possibile individuare i rischi associati ai dati sensibili. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Scopri di più"].



=== Nella pagina Data Investigation sono disponibili tre nuovi filtri

Sono disponibili nuovi filtri per perfezionare i risultati visualizzati nella pagina Data Investigation (analisi dati):

* Il filtro "numero di utenti con accesso" mostra i file e le cartelle aperti a un determinato numero di utenti. Puoi scegliere un intervallo di numeri per perfezionare i risultati, ad esempio per vedere quali file sono accessibili da 51-100 utenti.
* I filtri "ora di creazione", "ora di rilevamento", "ultima modifica" e "ultima accesso" consentono ora di creare un intervallo di date personalizzato invece di selezionare semplicemente un intervallo di giorni predefinito. Ad esempio, è possibile cercare i file con un'ora di creazione "più vecchia di 6 mesi" o con una data "ultima modifica" negli ultimi 10 giorni.
* Il filtro "percorso file" consente ora di specificare i percorsi che si desidera escludere dai risultati delle query filtrate. Se si inseriscono percorsi per includere ed escludere determinati dati, la classificazione BlueXP individua prima tutti i file nei percorsi inclusi, quindi rimuove i file dai percorsi esclusi e visualizza i risultati.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["Consulta l'elenco di tutti i filtri che puoi utilizzare per analizzare i tuoi dati"].



=== La classificazione BlueXP può identificare il numero individuale giapponese

La classificazione BlueXP è in grado di identificare e classificare i file che contengono il numero individuale giapponese (noto anche come My Number). Questo include sia il numero personale che il numero personale aziendale. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].



== 11 dicembre 2022 (versione 1.18)



=== Miglioramenti dell'installazione on-premise

Sono stati aggiunti i seguenti miglioramenti per l'installazione on-premise di Data Sense:

* Alcuni prerequisiti aggiuntivi vengono ora controllati prima dell'avvio dell'installazione su un host on-premise. In questo modo, è possibile assicurarsi che il sistema host sia pronto al 100% per l'installazione del software Data Sense:
+
** verificare la disponibilità di spazio sufficiente su `/var/lib/docker`, `/tmp`, e. `/opt`
** verificare le autorizzazioni pertinenti su tutte le cartelle richieste


* Nella pagina Configuration (Configurazione), la sezione Working Environments (ambienti di lavoro) visualizza ora l' _Working Environment ID_ (ID ambiente di lavoro) e il nome _scanner Group_ (Gruppo scanner). È necessario conoscere l'ID dell'ambiente di lavoro se si prevede di utilizzare più host Data Sense per fornire ulteriore potenza di elaborazione per eseguire la scansione delle origini dati.
* Inoltre, nella pagina di configurazione, una nuova sezione mostra i gruppi di scanner configurati e i nodi dello scanner presenti in ciascun gruppo.


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Scopri di più sull'installazione di Data Sense su un singolo server host e su più host"].



== 13 novembre 2022 (versione 1.17)



=== Supporto per la scansione degli account SharePoint on-premise

Data Sense è ora in grado di eseguire la scansione degli account SharePoint Online e degli account SharePoint on-premise (SharePoint Server). Se è necessario installare SharePoint sui propri server o in siti senza accesso a Internet, è ora possibile eseguire la scansione dei file utente di Data Sense in tali account. https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["Scopri di più"^].



=== Possibilità di eseguire una nuova scansione di più directory (cartelle o condivisioni)

Ora è possibile eseguire una nuova scansione di più directory (cartelle o condivisioni) immediatamente in modo che le modifiche vengano riflesse nel sistema. In questo modo è possibile assegnare la priorità alla nuova scansione di determinati dati prima di altri dati. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Scopri come eseguire nuovamente la scansione di una directory"^].



=== Possibilità di aggiungere ulteriori nodi "scanner" on-premise per eseguire la scansione di origini dati specifiche

Se Data Sense è stato installato in una posizione on-premise e si ha bisogno di una maggiore potenza di elaborazione della scansione per eseguire la scansione di determinate origini dati, è possibile aggiungere altri nodi "scanner" e assegnarli per eseguire la scansione di tali origini dati. È possibile aggiungere i nodi dello scanner subito dopo l'installazione del nodo manager oppure aggiungere un nodo scanner in un secondo momento.

Se necessario, i nodi dello scanner possono essere installati su sistemi host fisicamente più vicini alle origini dati che si stanno scansionando. Più vicino è il nodo dello scanner ai dati, meglio è perché riduce il più possibile la latenza di rete durante la scansione dei dati. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["Scopri come installare i nodi dello scanner per eseguire la scansione di origini dati aggiuntive"^].



=== I programmi di installazione on-premise eseguono ora un controllo preliminare prima di iniziare l'installazione

Durante l'installazione di Data Sense su un sistema Linux, l'installatore verifica se il sistema soddisfa tutti i requisiti necessari (CPU, RAM, capacità, rete, ecc.) prima di avviare l'installazione effettiva. In questo modo è possibile individuare i problemi *prima* che si spenda tempo per l'installazione.



== 6 settembre 2022 (versione 1.16)



=== Possibilità di eseguire una nuova scansione immediata di un repository per riflettere le modifiche apportate ai file

Se è necessario eseguire una nuova scansione di un determinato repository immediatamente in modo che le modifiche vengano riflesse nel sistema, è possibile selezionare il repository e rieseguire la scansione. In questo modo è possibile assegnare la priorità alla nuova scansione di determinati dati prima di altri dati. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Scopri come eseguire nuovamente la scansione di una directory"^].



=== Nuovo filtro per lo stato della scansione Data Sense nella pagina Data Investigation

Il filtro "Analysis Status" (Stato analisi) consente di elencare i file che si trovano in una fase specifica della scansione Data Sense. È possibile selezionare un'opzione per visualizzare l'elenco dei file che sono *Pending First Scan* (prima scansione in sospeso), *Completed* (completato), *Pending Rescan* (Nuova scansione in sospeso) o *Failed* (scansione non riuscita).

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Consulta l'elenco di tutti i filtri che puoi utilizzare per analizzare i tuoi dati"^].



=== I soggetti interessati ai dati sono ora considerati parte dei "dati personali" trovati nelle scansioni

Data Sense riconosce ora i soggetti dei dati come parte dei risultati personali visualizzati nella dashboard di conformità. Inoltre, quando si esegue una ricerca nella pagina delle indagini, è possibile selezionare "Data subjects" (soggetti dati) in "Personal Data" (dati personali) per visualizzare solo i file che contengono i soggetti dati.



=== I file breadcrumb Data Sense sono ora considerati parte delle "Categorie" presenti nelle scansioni

Data Sense ora riconosce i file breadcrumb come parte delle categorie che appaiono nella dashboard di conformità. Si tratta di file creati da Data Sense durante lo spostamento dei file dalla posizione di origine a una condivisione NFS. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Scopri di più su come vengono creati i file breadcrumb"^].

Inoltre, quando si esegue una ricerca nella pagina di analisi, è possibile selezionare "Data Sense Breadcrumb" (Breadcrumb rilevamento dati) in "Category" (Categoria) per visualizzare solo i file di breadcrumb Data Sense.



== 7 agosto 2022 (versione 1.15)



=== Cinque nuovi tipi di dati personali provenienti dalla Nuova Zelanda sono identificati da Data Sense

Data Sense è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* Numero di conto bancario della Nuova Zelanda
* Numero di patente di guida della Nuova Zelanda
* Numero IRD Nuova Zelanda (ID fiscale)
* New Zealand NHI (National Health Index)
* Numero di passaporto per la Nuova Zelanda


link:reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che Data Sense può identificare nei tuoi dati"].



=== Possibilità di aggiungere un file breadcrumb per indicare il motivo dello spostamento di un file

Quando si utilizza la funzione Data Sense per spostare i file di origine in una condivisione NFS, è ora possibile lasciare un file breadcrumb nella posizione del file spostato. Un file breadcrumb aiuta gli utenti a capire perché un file è stato spostato dalla posizione originale. Per ogni file spostato, il sistema crea un file breadcrumb nella posizione di origine denominata `<filename>-breadcrumb-<date>.txt` per visualizzare la posizione in cui è stato spostato il file e l'utente che lo ha spostato. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Scopri di più"^].



=== I dati personali e i dati personali sensibili presenti nelle rubriche vengono visualizzati nei risultati delle indagini

La pagina Data Investigation ora mostra i risultati dei dati personali e dei dati personali sensibili trovati nelle directory (cartelle e condivisioni). https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["Vedi un esempio qui"^].



=== Visualizzare lo stato di quanti volumi, bucket e così via sono stati classificati correttamente

Quando si visualizzano i singoli repository che Data Sense sta analizzando (volumi, bucket, ecc.), ora è possibile vedere quanti sono stati "mappati" e quanti sono stati "classificati". La classificazione richiede più tempo poiché l'identificazione ai completa viene eseguita su tutti i dati. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["Scopri come visualizzare queste informazioni"^].



=== Ora puoi aggiungere modelli personalizzati che Data Sense identificherà nei tuoi dati

Esistono due modi per aggiungere "dati personali" personalizzati che Data Sense identificherà nelle scansioni future. In questo modo è possibile visualizzare un quadro completo della posizione dei dati potenzialmente sensibili in tutti i file dell'organizzazione.

* È possibile aggiungere parole chiave personalizzate da un file di testo.
* È possibile aggiungere un modello personale utilizzando un'espressione regolare (regex).


Queste parole chiave e modelli vengono aggiunti ai modelli predefiniti esistenti già utilizzati da Data Sense e i risultati saranno visibili nella sezione modelli personali. https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Scopri di più"^].
