---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: Scopri le novità della classificazione BlueXP. 
---
= Novità della classificazione BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità della classificazione BlueXP.



== 12 maggio 2025



=== Versione 1,43

Questa versione di classificazione BlueXP  include:

.Assegnare la priorità alle scansioni di classificazione
La classificazione BlueXP  ora supporta la possibilità di assegnare priorità alle scansioni Map & Classify oltre alle scansioni Mapping-only, consentendo di selezionare quali scansioni vengono completate per prime. La prioritizzazione delle scansioni Map & Classify è supportata durante e prima dell'inizio delle scansioni. Se si sceglie di assegnare la priorità a una scansione mentre è in corso, vengono assegnate priorità sia alla scansione di mappatura che alla scansione di classificazione.

Per ulteriori informazioni, vedere link:task-managing-repo-scanning.html#prioritize-scans["Assegnare priorità alle scansioni"].

.Supporto per categorie di dati canadesi per l'identificazione personale (PII)
Le scansioni di classificazione BlueXP  ora identificano le categorie di dati canadesi PII per le informazioni bancarie, il numero di passaporto, il numero di assicurazione sociale, il numero di patente di guida e il numero di carta sanitaria per tutte le province e territori.

Per ulteriori informazioni, vedere xref:reference-private-data-categories.adoc#types-of-personal-data[Categorie di dati personali].

.Classificazione personalizzata (anteprima)
La classificazione BlueXP  supporta ora classificazioni personalizzate per le scansioni Map & Classify. Grazie alle classificazioni personalizzate, è possibile personalizzare le scansioni BlueXP  per acquisire dati specifici dell'organizzazione e garantire la conformità con le espressioni regolari. Questa funzione è attualmente in anteprima.

Per ulteriori informazioni, vedere xref:task-custom-classification.adoc[Aggiungere classificazioni personalizzate].

.Scheda ricerche salvate
La scheda **Policies** è stata rinominata xref:task-using-policies.html[**Ricerche salvate**]. La funzionalità è la stessa.

.Inviare gli eventi di scansione al registro di controllo
Gli eventi di scansione BlueXP  possono ora essere inviati a xref:task-audit-data-sense-actions.html[log di audit]. La classificazione BlueXP  supporta anche l'invio di eventi di classificazione (quando viene avviata e terminata una scansione) a link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Tempistiche di BlueXP "^]. L'invio degli eventi di scansione di classificazione alla timeline BlueXP  è supportato solo per gli ambienti di lavoro.

.Aggiornamenti di protezione
* Il pacchetto keras è stato aggiornato, attenuando le vulnerabilità (BDSA-2025-0107 e BDSA-2025-1984).
* La configurazione dei container Docker è stata aggiornata. Il contenitore non ha più accesso alle interfacce di rete dell'host per la creazione di pacchetti di rete grezzi. Riducendo gli accessi non necessari, l'aggiornamento riduce i potenziali rischi di protezione.


.Miglioramenti delle performance
I miglioramenti del codice sono stati implementati per ridurre l'utilizzo della RAM e migliorare le prestazioni complessive della classificazione BlueXP .

.Correzioni dei bug
Sono stati corretti i bug che hanno causato il mancato funzionamento delle scansioni StorageGRID, il mancato caricamento delle opzioni del filtro della pagina di analisi e la valutazione del rilevamento dati per le valutazioni di volumi elevati.



== 14 aprile 2025



=== Versione 1,42

Questa versione di classificazione BlueXP  include:

.Scansione in blocco per ambienti di lavoro
La classificazione BlueXP  supporta ora le operazioni di massa per gli ambienti di lavoro. È possibile scegliere di attivare le scansioni di mappatura, attivare le scansioni di mappatura e classificazione, disattivare le scansioni o creare una configurazione personalizzata tra i volumi in ambiente di lavoro. Se si effettua una selezione per un singolo volume, questa sovrascrive la selezione in blocco. Per eseguire un'operazione bulk, accedere alla pagina **Configurazione** ed effettuare la selezione.

.Scaricare il rapporto di indagine localmente
La classificazione BlueXP  ora supporta la possibilità di scaricare i report di analisi dei dati localmente per la visualizzazione nel browser. Se si sceglie l'opzione locale, l'analisi dei dati è disponibile solo nel formato CSV e visualizza solo le prime 10.000 righe di dati.

Per ulteriori informazioni, vedere link:task-investigate-data.html#create-the-data-investigation-report["Esaminare i dati memorizzati nella propria organizzazione con la classificazione BlueXP "].



== 10 marzo 2025



=== Versione 1,41

Questa versione di classificazione BlueXP  include miglioramenti generali e correzioni dei bug. Include inoltre:

.Stato scansione
La classificazione BlueXP  ora tiene traccia dell'avanzamento in tempo reale delle scansioni di mappatura e classificazione _iniziali_ su un volume. Le barre progressive separate tengono traccia delle scansioni di mappatura e classificazione, presentando una percentuale di file totali sottoposti a scansione. È inoltre possibile passare il mouse su una barra di avanzamento per visualizzare il numero di file sottoposti a scansione e il numero totale di file. Il monitoraggio dello stato delle scansioni consente di ottenere informazioni più approfondite sull'avanzamento della scansione, consentendo di pianificare meglio le scansioni e di comprendere l'allocazione delle risorse.

Per visualizzare lo stato delle scansioni, accedere a **Configurazione** nella classificazione BlueXP , quindi selezionare **Configurazione ambiente di lavoro**. L'avanzamento viene visualizzato in linea per ogni volume.



== 19 febbraio 2025



=== Versione 1,40

Questa versione di classificazione BlueXP  include i seguenti aggiornamenti.

.Supporto per RHEL 9,5
Questa versione fornisce il supporto per Red Hat Enterprise Linux v9,5 oltre alle versioni precedentemente supportate. Ciò è applicabile a qualsiasi installazione manuale in loco della classificazione BlueXP , comprese le implementazioni in ambienti oscuri.

I seguenti sistemi operativi richiedono l'utilizzo del motore del contenitore Podman e richiedono la classificazione BlueXP  versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 e 9,5.

.Assegnare priorità alle scansioni di sola mappatura
Quando si eseguono scansioni solo mapping, è possibile assegnare la priorità alle scansioni più importanti. Questa funzione è utile quando si hanno molti ambienti di lavoro e si desidera garantire che le scansioni ad alta priorità vengano completate per prime.

Per impostazione predefinita, le scansioni vengono accodate in base all'ordine in cui vengono avviate. Grazie alla possibilità di assegnare priorità alle scansioni, è ora possibile spostarle in primo piano sulla coda. È possibile assegnare priorità a più scansioni. La priorità viene indicata in un ordine di primo ingresso e primo uscita, ovvero la prima scansione assegnata all'utente viene spostata in primo piano nella coda; la seconda scansione assegnata all'utente diventa seconda nella coda e così via.

La priorità viene concessa una tantum. Le riscansioni automatiche dei dati di mappatura vengono eseguite nell'ordine predefinito.

La prioritizzazione è limitata a link:concept-cloud-compliance.html["scansioni di sola mappatura"]; non è disponibile per le scansioni mappa e classificazione.

Per ulteriori informazioni, vedere link:task-managing-repo-scanning.html#prioritize-scans["Assegnare priorità alle scansioni"].

.Riprovare tutte le scansioni
La classificazione BlueXP  ora supporta la possibilità di ripetere in batch tutte le scansioni non riuscite.

È ora possibile ritentare le scansioni in un'operazione batch con la funzione **Riprova tutto**. Se le scansioni di classificazione non vengono eseguite correttamente a causa di un problema temporaneo, ad esempio un'interruzione della rete, è possibile riprovare tutte le scansioni contemporaneamente con un solo pulsante invece di riprovare singolarmente. Le scansioni possono essere riavviate tutte le volte necessarie.

Per riprovare tutte le scansioni:

. Dal menu classificazione BlueXP , selezionare *Configurazione*.
. Per riprovare tutte le scansioni non riuscite, selezionare *Riprova tutte le scansioni*.


.Migliore precisione del modello di categorizzazione
La precisione del modello di machine learning per link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["categorie predefinite"] è migliorata del 11%.



== 22 gennaio 2025



=== Versione 1,39

Questa versione di classificazione BlueXP  aggiorna il processo di esportazione per il rapporto analisi dati. Questo aggiornamento per l'esportazione è utile per eseguire analisi aggiuntive sui dati, creare visualizzazioni aggiuntive sui dati o condividere con altri i risultati dell'analisi dei dati.

In precedenza, l'esportazione del rapporto Data Investigation era limitata a 10.000 righe. Con questa versione, il limite è stato rimosso in modo da poter esportare tutti i dati. Questa modifica consente di esportare più dati dai report di analisi dei dati, offrendo maggiore flessibilità nell'analisi dei dati.

È possibile scegliere l'ambiente di lavoro, i volumi, la cartella di destinazione e il formato JSON o CSV. Il nome file esportato include un indicatore data e ora che consente di identificare quando i dati sono stati esportati.

Gli ambienti di lavoro supportati includono:

* Cloud Volumes ONTAP
* FSX per ONTAP
* ONTAP
* Gruppo di condivisione


L'esportazione dei dati dal rapporto di analisi dei dati presenta le seguenti limitazioni:

* Il numero massimo di record da scaricare è di 500 milioni. Per tipo (file, directory e tabelle)
* Si prevede che l'esportazione di un milione di record richiederà circa 35 minuti.


Per informazioni dettagliate sull'analisi dei dati e sul rapporto, vedere https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Esaminare i dati memorizzati nella propria organizzazione"].



== 16 dicembre 2024



=== Versione 1,38

Questa versione di classificazione BlueXP  include miglioramenti generali e correzioni dei bug.



== 4 novembre 2024



=== Versione 1,37

Questa versione di classificazione BlueXP  include i seguenti aggiornamenti.

.Supporto per RHEL 8,10
Questa versione fornisce il supporto per Red Hat Enterprise Linux v8,10 oltre alle versioni precedentemente supportate. Ciò è applicabile a qualsiasi installazione manuale in loco della classificazione BlueXP , comprese le implementazioni in ambienti oscuri.

I seguenti sistemi operativi richiedono l'utilizzo del motore del contenitore Podman e richiedono la classificazione BlueXP  versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 8,10, 9,0, 9,1, 9,2, 9,3 e 9,4.

Ulteriori informazioni su https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Classificazione BlueXP"].

.Supporto di NFS v4,1
Questa release fornisce supporto per NFS v4,1 oltre alle versioni precedentemente supportate.

Ulteriori informazioni su https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Classificazione BlueXP"].



== 10 ottobre 2024



=== Versione 1,36

.Supporto per RHEL 9,4
Questa versione fornisce il supporto per Red Hat Enterprise Linux v9,4 oltre alle versioni precedentemente supportate. Ciò è applicabile a qualsiasi installazione manuale in loco della classificazione BlueXP , comprese le implementazioni in ambienti oscuri.

I seguenti sistemi operativi richiedono l'utilizzo del motore del contenitore Podman e richiedono la classificazione BlueXP  versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 9,0, 9,1, 9,2, 9,3 e 9,4.

Scopri di più https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Panoramica sulle implementazioni di classificazione BlueXP"].

.Prestazioni di scansione migliorate
Questa versione offre prestazioni di scansione migliorate.



== 2 settembre 2024



=== Versione 1,35

.Eseguire la scansione dei dati StorageGRID
La classificazione BlueXP  può ora eseguire la scansione dei dati in StorageGRID.

Per ulteriori informazioni, fare riferimento alla link:task-scanning-storagegrid.html["Eseguire la scansione dei dati StorageGRID"].



== 5 agosto 2024



=== Versione 1,34

Questa versione di classificazione BlueXP  include il seguente aggiornamento.

.Passare da CentOS a Ubuntu
La classificazione BlueXP  ha aggiornato il proprio sistema operativo Linux per Microsoft Azure e Google Cloud Platform (GCP) da CentOS 7,9 a Ubuntu 22,04.

Per informazioni dettagliate sulla distribuzione, fare riferimento a https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["Installare su un host Linux con accesso a Internet e preparare il sistema host Linux"].



== 1 luglio 2024



=== Versione 1,33

.Ubuntu supportato
Questa versione supporta la piattaforma Linux Ubuntu 24,04.

.Le scansioni di mappatura raccolgono i metadati
I seguenti metadati vengono estratti dai file durante le scansioni di mappatura e visualizzati nelle dashboard Governance, Compliance e Investigation:

* Ambiente di lavoro
* Tipo di ambiente di lavoro
* Repository di storage
* Tipo di file
* Capacità utilizzata
* Numero di file
* Dimensione del file
* Creazione di file
* Ultimo accesso al file
* Ultima modifica al file
* Ora di rilevamento file
* Estrazione delle autorizzazioni


.Dati aggiuntivi nelle dashboard
Questa versione aggiorna i dati visualizzati nei dashboard Governance, Compliance e Investigation durante le scansioni di mappatura.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Qual è la differenza tra la mappatura e la classificazione delle scansioni"].



== 5 giugno 2024



=== Versione 1,32

.Nuova colonna Stato mapping nella pagina di configurazione
In questa versione viene ora visualizzata una nuova colonna Stato mapping nella pagina di configurazione. La nuova colonna consente di identificare se la mappatura è in esecuzione, in coda, in pausa o superiore.

Per la spiegazione degli stati, vedere https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["Modificare le impostazioni di scansione"].



== 15 maggio 2024



=== Versione 1,31

.La classificazione è disponibile come servizio core all'interno di BlueXP
La classificazione BlueXP è ora disponibile come funzionalità core all'interno di BlueXP senza costi aggiuntivi per un massimo di 500 TiB di dati sottoposti a scansione. Non è richiesta alcuna licenza di classificazione o abbonamento a pagamento. Mentre concentriamo la funzionalità di classificazione BlueXP sulla scansione dei sistemi storage NetApp con questa nuova versione, alcune funzionalità legacy saranno disponibili solo per i clienti che avevano precedentemente pagato per una licenza. L'utilizzo di tali funzioni legacy scadrà quando il contratto a pagamento avrà raggiunto la data di fine.

link:reference-free-paid.html["Ulteriori informazioni sulle funzioni obsolete"].



== 1 aprile 2024



=== Versione 1,30

.Supporto aggiunto per la classificazione RHEL v8,8 e v9,3 BlueXP
Questa versione fornisce il supporto per Red Hat Enterprise Linux v8,8 e v9,3 oltre a 9.x, che richiede Podman, anziché il motore Docker. Applicabile a qualsiasi installazione manuale on-premise della classificazione BlueXP.

I seguenti sistemi operativi richiedono l'utilizzo del motore del container Podman e richiedono la classificazione BlueXP versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 9,0, 9,1, 9,2 e 9,3.

Scopri di più https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Panoramica sulle implementazioni di classificazione BlueXP"].

La classificazione BlueXP è supportata se installi il connettore su un host RHEL 8 o 9 che risiede on-premise. Non è supportato se l'host RHEL 8 o 9 si trova in AWS, Azure o Google Cloud.

.Opzione per attivare la raccolta del registro di controllo rimossa
L'opzione per attivare la raccolta del registro di controllo è stata disattivata.

.Velocità di scansione migliorata
Le prestazioni di scansione sui nodi scanner secondari sono state migliorate. È possibile aggiungere ulteriori nodi scanner se è necessaria una potenza di elaborazione aggiuntiva per le scansioni. Per ulteriori informazioni, fare riferimento a. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installare la classificazione BlueXP su un host con accesso a Internet"].

.Aggiornamenti automatici
Se hai implementato la classificazione BlueXP su un sistema con accesso Internet, il sistema si aggiorna automaticamente. In precedenza, l'aggiornamento si è verificato dopo un tempo specifico trascorso dall'ultima attività dell'utente. Con questa release, la classificazione BlueXP si aggiorna automaticamente se l'ora locale è compresa tra le 9:1:00 e le 9:5:00. Se l'ora locale è al di fuori di queste ore, l'aggiornamento avviene dopo un intervallo di tempo specifico trascorso dall'ultima attività dell'utente. Per ulteriori informazioni, fare riferimento a. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installazione su un host Linux con accesso a Internet"].

Se hai implementato la classificazione BlueXP senza accesso a Internet, dovrai eseguire l'aggiornamento manualmente. Per ulteriori informazioni, fare riferimento a. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["Installare la classificazione BlueXP su un host Linux senza accesso Internet"].



== 4 marzo 2024



=== Versione 1,29

.Ora è possibile escludere la scansione dei dati che risiedono in determinate directory di origine dati
Se si desidera che la classificazione BlueXP escluda la scansione dei dati che risiedono in determinate directory di origine dati, è possibile aggiungere questi nomi di directory a un file di configurazione elaborato dalla classificazione BlueXP. Questa funzione consente di evitare la scansione di directory non necessarie o che potrebbero generare risultati falsi positivi per i dati personali.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["Scopri di più"].

.Il supporto di istanze di grandi dimensioni è ora qualificato
Se hai bisogno della classificazione BlueXP per analizzare più di 250 milioni di file, puoi utilizzare un'istanza Extra Large nell'implementazione del cloud o nell'installazione on-premise. Questo tipo di sistema è in grado di eseguire la scansione di un massimo di 500 milioni di file.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Scopri di più"].



== 10 gennaio 2024



=== Versione 1,27

.I risultati della pagina di analisi ora visualizzano le dimensioni totali oltre al numero totale di elementi
I risultati filtrati nella pagina di analisi ora mostrano la dimensione totale degli elementi oltre al numero totale di file. Ciò può essere utile quando si spostano file, si eliminano file e altro ancora.

.Configurare gli ID gruppo aggiuntivi come "aperti all'organizzazione"
Ora puoi configurare gli ID di gruppo in NFS in modo che siano considerati "aperti all'organizzazione" direttamente dalla classificazione BlueXP se il gruppo non era stato inizialmente impostato con tale autorizzazione. Tutti i file e le cartelle con questi ID di gruppo allegati verranno visualizzati come "Apri all'organizzazione" nella pagina Dettagli analisi. Scopri come https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["Aggiungere altri ID gruppo come "aperti all'organizzazione""].



== 14 dicembre 2023



=== Versione 1.26.6

Questa versione includeva alcuni miglioramenti minori.

La release ha inoltre rimosso le seguenti opzioni:

* L'opzione per attivare la raccolta del registro di controllo è stata disattivata.
* Durante l'analisi Directory, l'opzione per calcolare il numero di dati personali identificabili (PII) per directory non è disponibile. Fare riferimento alla link:task-investigate-data.html["Esaminare i dati memorizzati nella propria organizzazione"].
* L'opzione per integrare i dati utilizzando le etichette AIP (Azure Information Protection) è stata disattivata. Fare riferimento a. link:task-org-private-data.html["Organizzare i dati privati"].




== 6 novembre 2023



=== Versione 1.26.3

In questa versione sono stati risolti i seguenti problemi

* È stata risolta un'incoerenza quando si presenta il numero di file sottoposti a scansione dal sistema nei dashboard.
* Miglioramento del comportamento di scansione mediante la gestione e la creazione di report su file e directory con caratteri speciali nel nome e nei metadati.




== 4 ottobre 2023



=== Versione 1,26

.Supporto per le installazioni on-premise della classificazione BlueXP su RHEL versione 9
Le versioni 8 e 9 di Red Hat Enterprise Linux non supportano il motore Docker, necessario per l'installazione della classificazione BlueXP. Ora supportiamo l'installazione della classificazione BlueXP su RHEL 9,0, 9,1 e 9,2 utilizzando Podman versione 4 o superiore come infrastruttura container. Se il tuo ambiente richiede l'utilizzo delle versioni più recenti di RHEL, ora puoi installare la classificazione BlueXP (versione 1,26 o superiore) quando utilizzi Podman.

Al momento non supportiamo installazioni in siti oscuri o ambienti di scansione distribuiti (utilizzando nodi di scansione master e remoti) quando si utilizza RHEL 9.x.



== 5 settembre 2023



=== Versione 1,25

.Implementazioni di piccole e medie dimensioni temporaneamente non disponibili
Quando implementi un'istanza di classificazione BlueXP in AWS, al momento non è disponibile l'opzione per selezionare *implementa > Configurazione* e scegliere un'istanza di piccole o medie dimensioni. È comunque possibile distribuire l'istanza utilizzando le dimensioni dell'istanza di grandi dimensioni selezionando *distribuisci > distribuisci*.

.Applicare le etichette su un massimo di 100.000 elementi dalla pagina risultati analisi
In passato, nella pagina dei risultati dell'analisi era possibile applicare tag a una singola pagina alla volta (20 elementi). Ora è possibile selezionare *tutti* elementi nelle pagine dei risultati dell'analisi e applicare tag a tutti gli elementi, fino a 100.000 elementi alla volta. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["Scopri come"].

.Identificare i file duplicati con una dimensione minima di 1 MB
Classificazione BlueXP utilizzata per identificare i file duplicati solo quando avevano 50 MB o più. Ora è possibile identificare i file duplicati che iniziano con 1 MB. È possibile utilizzare i filtri della pagina di analisi "dimensione file" insieme a "duplicati" per vedere quali file di una certa dimensione sono duplicati nell'ambiente in uso.



== 17 luglio 2023



=== Versione 1,24

.Due nuovi tipi di dati personali tedeschi sono identificati dalla classificazione BlueXP
La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* ID tedesco (Personalausweisnummer)
* Numero tedesco di previdenza sociale (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].

.La classificazione BlueXP è completamente supportata in modalità limitata e privata
La classificazione BlueXP è ora completamente supportata nei siti senza accesso a Internet (modalità privata) e con accesso Internet in uscita limitato (modalità limitata). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri di più sulle modalità di implementazione di BlueXP per il connettore"^].

.Possibilità di saltare le versioni durante l'aggiornamento di un'installazione in modalità privata della classificazione BlueXP
Ora è possibile eseguire l'aggiornamento a una versione più recente della classificazione BlueXP anche se non è sequenziale. Ciò significa che l'attuale limite di aggiornamento della classificazione BlueXP per una versione alla volta non è più necessario. Questa funzione è rilevante a partire dalla versione 1.24 in poi.

.L'API di classificazione BlueXP è ora disponibile
L'API di classificazione BlueXP ti consente di eseguire azioni, creare query ed esportare informazioni sui dati che stai analizzando. La documentazione interattiva è disponibile utilizzando Swagger. La documentazione è suddivisa in più categorie, tra cui analisi, conformità, governance e configurazione. Ogni categoria è un riferimento alle schede nell'interfaccia utente di classificazione BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["Scopri di più sulle API di classificazione BlueXP"].



== 6 giugno 2023



=== Versione 1,23

.Il giapponese è ora supportato durante la ricerca dei nomi dei soggetti dei dati
I nomi giapponesi possono ora essere inseriti quando si cerca il nome di un soggetto in risposta a una richiesta di accesso soggetto a dati (DSAR). È possibile generare un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["Report Data Subject Access Request"] con le informazioni risultanti. È anche possibile immettere nomi giapponesi in https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Filtro "Data Subject" nella pagina Data Investigation"] per identificare i file che contengono il nome del soggetto.

.Ubuntu è ora una distribuzione Linux supportata su cui è possibile installare la classificazione BlueXP
Ubuntu 22.04 è stato qualificato come sistema operativo supportato per la classificazione BlueXP. È possibile installare la classificazione BlueXP su un host Ubuntu Linux nella rete o su un host Linux nel cloud quando si utilizza la versione 1.23 del programma di installazione. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Scopri come installare la classificazione BlueXP su un host con Ubuntu installato"].

.Red Hat Enterprise Linux 8.6 e 8.7 non sono più supportati con le nuove installazioni di classificazione BlueXP
Queste versioni non sono supportate con le nuove implementazioni perché Red Hat non supporta più Docker, che è un prerequisito. Se si dispone di una macchina di classificazione BlueXP esistente in esecuzione su RHEL 8.6 o 8.7, NetApp continuerà a supportare la configurazione.

.La classificazione BlueXP può essere configurata come FPolicy Collector per ricevere eventi FPolicy dai sistemi ONTAP
È possibile consentire la raccolta dei registri di controllo dell'accesso ai file nel sistema di classificazione BlueXP per gli eventi di accesso ai file rilevati sui volumi negli ambienti di lavoro. La classificazione BlueXP può acquisire i seguenti tipi di eventi FPolicy e gli utenti che hanno eseguito le azioni sui file: Creare, leggere, scrivere, eliminare, rinominare, Modificare il proprietario/le autorizzazioni e modificare SACL/DACL.

.Le licenze Data Sense BYOL sono ora supportate nei siti bui
Ora puoi caricare la tua licenza BYOL Data Sense nel portafoglio digitale BlueXP in un sito buio, in modo da ricevere una notifica quando la tua licenza sta per esaurirsi.



== 3 aprile 2023



=== Versione 1,22

.Nuovo report sulla valutazione del rilevamento dei dati
Il Data Discovery Assessment Report fornisce un'analisi di alto livello dell'ambiente sottoposto a scansione per evidenziare i risultati del sistema e mostrare le aree problematiche e le potenziali fasi di risoluzione dei problemi. L'obiettivo di questo report è di sensibilizzare i clienti sulle problematiche di governance dei dati, sulle esposizioni alla sicurezza dei dati e sulle lacune di conformità dei dati del set di dati. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Scopri come generare e utilizzare il Data Discovery Assessment Report"].

.Possibilità di implementare la classificazione BlueXP su istanze più piccole nel cloud
Quando si implementa la classificazione BlueXP da un connettore BlueXP in un ambiente AWS, è ora possibile scegliere tra due tipi di istanze più piccoli rispetto a quelli disponibili con l'istanza predefinita. Se si esegue la scansione di un ambiente di piccole dimensioni, questo può contribuire a risparmiare sui costi del cloud. Tuttavia, ci sono alcune limitazioni quando si utilizza l'istanza più piccola. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Vedere i tipi di istanze e le limitazioni disponibili"].

.È ora disponibile uno script standalone per qualificare il sistema Linux prima dell'installazione della classificazione BlueXP
Se si desidera verificare che il sistema Linux soddisfi tutti i prerequisiti indipendentemente dall'esecuzione dell'installazione di classificazione BlueXP, è possibile scaricare uno script separato che esegue solo i prerequisiti. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Scopri come verificare se il tuo host Linux è pronto per installare la classificazione BlueXP"].



== 7 marzo 2023



=== Versione 1,21

.Nuova funzionalità per aggiungere categorie personalizzate dall'interfaccia utente di classificazione BlueXP
La classificazione BlueXP consente ora di aggiungere le proprie categorie personalizzate in modo che la classificazione BlueXP identifichi i file che si adattano a tali categorie. La classificazione BlueXP  dispone di molti https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["categorie predefinite"], quindi questa funzione consente di aggiungere categorie personalizzate per identificare la posizione in cui vengono trovate le informazioni univoche dell'organizzazione.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Scopri di più"^].

.Ora è possibile aggiungere parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP
La classificazione BlueXP ha avuto la possibilità di aggiungere parole chiave personalizzate che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare un'interfaccia a riga di comando per aggiungere le parole chiave. In questa release, la possibilità di aggiungere parole chiave personalizzate è nell'interfaccia utente di classificazione di BlueXP, rendendo molto semplice aggiungere e modificare queste parole chiave.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Scopri di più sull'aggiunta di parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP"^].

.Possibilità di eseguire la classificazione BlueXP *non* dei file di scansione quando verrà modificato l'ultimo tempo di accesso
Per impostazione predefinita, se la classificazione di BlueXP non dispone di permessi di "scrittura" adeguati, il sistema non esegue la scansione dei file nei volumi perché la classificazione di BlueXP non può riportare l'ultimo tempo di accesso alla data e ora originale. Tuttavia, se non si ha alcun problema se l'ultimo tempo di accesso viene ripristinato all'ora originale nei file, è possibile ignorare questo comportamento nella pagina di configurazione in modo che la classificazione BlueXP scansiona i volumi indipendentemente dalle autorizzazioni.

In combinazione con questa funzionalità, è stato aggiunto un nuovo filtro denominato "Scan Analysis Event", che consente di visualizzare i file non classificati perché la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso o i file classificati anche se la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html["Scopri di più su "Last Access Time timestamp" e sulle autorizzazioni richieste dalla classificazione BlueXP"].

.Tre nuovi tipi di dati personali sono identificati dalla classificazione BlueXP
La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* Numero della carta d'identità del Botswana (Omang)
* Numero passaporto Botswana
* Singapore National Registration Identity Card (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].

.Funzionalità aggiornate per le directory
* L'opzione "Light CSV Report" (Report CSV leggero) per i report di analisi dei dati include ora le informazioni provenienti dalle directory.
* Il filtro dell'ora "ultimo accesso" ora mostra l'ora dell'ultimo accesso per file e directory.


.Miglioramenti all'installazione
* Il programma di installazione della classificazione BlueXP per i siti senza accesso a Internet (siti oscuri) ora esegue un controllo preliminare per assicurarsi che i requisiti di sistema e di rete siano stati soddisfatti per un'installazione corretta.
* I file di log di audit dell'installazione vengono salvati ora e scritti in `/ops/netapp/install_logs`.




== 5 febbraio 2023



=== Versione 1,20

.Possibilità di inviare e-mail di notifica basate su policy a qualsiasi indirizzo e-mail
Nelle versioni precedenti della classificazione BlueXP, è possibile inviare avvisi e-mail agli utenti BlueXP del proprio account quando alcuni criteri critici restituiscono risultati. Questa funzione ti consente di ricevere notifiche per proteggere i tuoi dati quando non sei online. Ora puoi anche inviare avvisi e-mail dalle policy a qualsiasi altro utente (fino a 20 indirizzi e-mail) che non sia presente nel tuo account BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["Scopri di più sull'invio di avvisi e-mail in base ai risultati della policy"].

.Ora è possibile aggiungere modelli personali dall'interfaccia utente di classificazione BlueXP
La classificazione BlueXP ha avuto la possibilità di aggiungere "dati personali" personalizzati che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare una riga di comando per aggiungere i modelli personalizzati. In questa release, la possibilità di aggiungere modelli personali utilizzando un regex è nell'interfaccia utente di classificazione BlueXP, rendendo molto semplice aggiungere e modificare questi modelli personalizzati.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Scopri di più sull'aggiunta di modelli personalizzati dall'interfaccia utente di classificazione BlueXP"^].

.Possibilità di spostare 15 milioni di file utilizzando la classificazione BlueXP
In passato era possibile che la classificazione BlueXP spostasse un massimo di 100,000 file di origine in qualsiasi condivisione NFS. Ora puoi spostare fino a 15 milioni di file alla volta. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["Scopri di più sullo spostamento dei file di origine utilizzando la classificazione BlueXP"].

.Possibilità di visualizzare il numero di utenti che hanno accesso ai file di SharePoint Online
Il filtro "numero di utenti con accesso" ora supporta i file memorizzati nei repository SharePoint Online. In passato erano supportati solo i file su condivisioni CIFS. Si noti che i gruppi SharePoint che non sono basati su Active Directory non verranno conteggiati in questo filtro al momento.

.Il nuovo stato "Partial Success" (operazione riuscita parziale) è stato aggiunto al pannello Action Status (Stato azione)
Il nuovo stato "Partial Success" (successo parziale) indica che un'azione di classificazione BlueXP è terminata e che alcuni elementi hanno avuto esito negativo, ad esempio quando si spostano o si eliminano file 100. Inoltre, lo stato "Finished" (terminato) è stato rinominato "Success" (riuscito). In passato, lo stato "Finished" (terminato) potrebbe elencare le azioni riuscite e non riuscite. Ora lo stato "Success" significa che tutte le azioni sono riuscite su tutti gli elementi. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Vedere come visualizzare il pannello Actions Status (Stato azioni)"].



== 9 gennaio 2023



=== Versione 1,19

.Possibilità di visualizzare un grafico di file che contengono dati sensibili e che sono eccessivamente permissivi
La dashboard di governance ha aggiunto una nuova area _dati sensibili e permessi estesi_ che fornisce una mappa termica dei file che contengono dati sensibili (inclusi dati personali sensibili e sensibili) e che sono eccessivamente permissivi. Questo può aiutare a capire dove si possono avere alcuni rischi con i dati sensibili. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Scopri di più"].

.Nella pagina Data Investigation sono disponibili tre nuovi filtri
Sono disponibili nuovi filtri per perfezionare i risultati visualizzati nella pagina Data Investigation (analisi dati):

* Il filtro "numero di utenti con accesso" mostra i file e le cartelle aperti a un determinato numero di utenti. Puoi scegliere un intervallo di numeri per perfezionare i risultati, ad esempio per vedere quali file sono accessibili da 51-100 utenti.
* I filtri "ora di creazione", "ora di rilevamento", "ultima modifica" e "ultima accesso" consentono ora di creare un intervallo di date personalizzato invece di selezionare semplicemente un intervallo di giorni predefinito. Ad esempio, è possibile cercare i file con un'ora di creazione "più vecchia di 6 mesi" o con una data "ultima modifica" negli ultimi 10 giorni.
* Il filtro "percorso file" consente ora di specificare i percorsi che si desidera escludere dai risultati delle query filtrate. Se si inseriscono percorsi per includere ed escludere determinati dati, la classificazione BlueXP individua prima tutti i file nei percorsi inclusi, quindi rimuove i file dai percorsi esclusi e visualizza i risultati.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Consulta l'elenco di tutti i filtri che puoi utilizzare per analizzare i tuoi dati"].

.La classificazione BlueXP può identificare il numero individuale giapponese
La classificazione BlueXP è in grado di identificare e classificare i file che contengono il numero individuale giapponese (noto anche come My Number). Ciò include sia il numero personale che il numero aziendale. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].
