---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, bluexp, bluexp classification' 
summary: Scopri le novità della classificazione BlueXP. 
---
= Novità della classificazione BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità della classificazione BlueXP (Cloud Data Sense).



== 1 aprile 2024 (versione 1,30)



=== Supporto aggiunto per la classificazione RHEL v8,8 e v9,3 BlueXP

Questa versione fornisce il supporto per Red Hat Enterprise Linux v8,8 e v9,3 oltre a 9.x, che richiede Podman, anziché il motore Docker.

Applicabile a qualsiasi installazione manuale on-premise della classificazione BlueXP.

I seguenti sistemi operativi richiedono l'utilizzo del motore del container Podman e richiedono la classificazione BlueXP versione 1,30 o superiore: Red Hat Enterprise Linux versione 8,8, 9,0, 9,1, 9,2 e 9,3.

Scopri di più link:task-deploy-overview.html["Panoramica sulle implementazioni di classificazione BlueXP"].



=== Opzione per attivare la raccolta del registro di controllo rimossa

L'opzione per attivare la raccolta del registro di controllo è stata disattivata.



== 4 marzo 2024 (versione 1,29)



=== Ora è possibile escludere la scansione dei dati che risiedono in determinate directory di origine dati

Se si desidera che la classificazione BlueXP escluda la scansione dei dati che risiedono in determinate directory di origine dati, è possibile aggiungere questi nomi di directory a un file di configurazione elaborato dalla classificazione BlueXP. Questa funzione consente di evitare la scansione di directory non necessarie o che potrebbero generare risultati falsi positivi per i dati personali.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["Scopri di più"].



=== Il supporto di istanze di grandi dimensioni è ora qualificato

Se hai bisogno della classificazione BlueXP per analizzare più di 250 milioni di file, puoi utilizzare un'istanza Extra Large nell'implementazione del cloud o nell'installazione on-premise. Questo tipo di sistema è in grado di eseguire la scansione di un massimo di 500 milioni di file.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Scopri di più"].



== 10 gennaio 2024 (versione 1,27)



=== I risultati della pagina di analisi ora visualizzano le dimensioni totali oltre al numero totale di elementi

I risultati filtrati nella pagina di analisi ora mostrano la dimensione totale degli elementi oltre al numero totale di file. Ciò può essere utile quando si spostano file, si eliminano file e altro ancora.



=== Configurare gli ID gruppo aggiuntivi come "aperti all'organizzazione"

Ora puoi configurare gli ID di gruppo in NFS in modo che siano considerati "aperti all'organizzazione" direttamente dalla classificazione BlueXP se il gruppo non era stato inizialmente impostato con tale autorizzazione. Tutti i file e le cartelle con questi ID di gruppo allegati verranno visualizzati come "Apri all'organizzazione" nella pagina Dettagli analisi. Scopri come https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["Aggiungere altri ID gruppo come "aperti all'organizzazione""].



== 14 dicembre 2023 (versione 1.26.6)

Questa versione includeva alcuni miglioramenti minori.

Inoltre, la versione ha temporaneamente rimosso le seguenti opzioni:

* L'opzione per attivare la raccolta del registro di controllo è stata disattivata. Fare riferimento a. link:task-manage-file-access-events.html["Monitorare e gestire gli eventi di accesso ai file"].
* Durante l'analisi Directory, l'opzione per calcolare il numero di dati personali identificabili (PII) per directory non è disponibile. Fare riferimento a. link:task-investigate-data.html#filter-data-by-sensitivity-and-content["Esaminare i dati memorizzati nella propria organizzazione"].
* L'opzione per integrare i dati utilizzando le etichette AIP (Azure Information Protection) è stata disattivata. Fare riferimento a. link:task-org-private-data.html["Organizzare i dati privati"].




== 6 novembre 2023 (versione 1.26.3)



=== In questa versione sono stati risolti i seguenti problemi

* È stata risolta un'incoerenza quando si presenta il numero di file sottoposti a scansione dal sistema nei dashboard.
* Miglioramento del comportamento di scansione mediante la gestione e la creazione di report su file e directory con caratteri speciali nel nome e nei metadati.




== 4 ottobre 2023 (versione 1,26)



=== Supporto per le installazioni on-premise della classificazione BlueXP su RHEL versione 9

Le versioni 8 e 9 di Red Hat Enterprise Linux non supportano il motore Docker, necessario per l'installazione della classificazione BlueXP. Ora supportiamo l'installazione della classificazione BlueXP su RHEL 9,0, 9,1 e 9,2 utilizzando Podman versione 4 o superiore come infrastruttura container. Se il tuo ambiente richiede l'utilizzo delle versioni più recenti di RHEL, ora puoi installare la classificazione BlueXP (versione 1,26 o superiore) quando utilizzi Podman.

Al momento non supportiamo installazioni in siti oscuri o ambienti di scansione distribuiti (utilizzando nodi di scansione master e remoti) quando si utilizza RHEL 9.x.



== 5 settembre 2023 (versione 1,25)



=== Implementazioni di piccole e medie dimensioni temporaneamente non disponibili

Quando implementi un'istanza di classificazione BlueXP in AWS, al momento non è disponibile l'opzione per selezionare *implementa > Configurazione* e scegliere un'istanza di piccole o medie dimensioni. È comunque possibile distribuire l'istanza utilizzando le dimensioni dell'istanza di grandi dimensioni selezionando *distribuisci > distribuisci*.



=== Applicare le etichette su un massimo di 100.000 elementi dalla pagina risultati analisi

In passato, nella pagina dei risultati dell'analisi era possibile applicare tag a una singola pagina alla volta (20 elementi). Ora è possibile selezionare *tutti* elementi nelle pagine dei risultati dell'analisi e applicare tag a tutti gli elementi, fino a 100.000 elementi alla volta. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["Scopri come"].



=== Identificare i file duplicati con una dimensione minima di 1 MB

Classificazione BlueXP utilizzata per identificare i file duplicati solo quando avevano 50 MB o più. Ora è possibile identificare i file duplicati che iniziano con 1 MB. È possibile utilizzare i filtri della pagina di analisi "dimensione file" insieme a "duplicati" per vedere quali file di una certa dimensione sono duplicati nell'ambiente in uso.



== 17 luglio 2023 (versione 1.24)



=== Due nuovi tipi di dati personali tedeschi sono identificati dalla classificazione BlueXP

La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* ID tedesco (Personalausweisnummer)
* Numero tedesco di previdenza sociale (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].



=== La classificazione BlueXP è completamente supportata in modalità limitata e privata

La classificazione BlueXP è ora completamente supportata nei siti senza accesso a Internet (modalità privata) e con accesso Internet in uscita limitato (modalità limitata). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri di più sulle modalità di implementazione di BlueXP per il connettore"^].



=== Possibilità di saltare le versioni durante l'aggiornamento di un'installazione in modalità privata della classificazione BlueXP

Ora è possibile eseguire l'aggiornamento a una versione più recente della classificazione BlueXP anche se non è sequenziale. Ciò significa che l'attuale limite di aggiornamento della classificazione BlueXP per una versione alla volta non è più necessario. Questa funzione è rilevante a partire dalla versione 1.24 in poi.



=== L'API di classificazione BlueXP è ora disponibile

L'API di classificazione BlueXP ti consente di eseguire azioni, creare query ed esportare informazioni sui dati che stai analizzando. La documentazione interattiva è disponibile utilizzando Swagger. La documentazione è suddivisa in più categorie, tra cui analisi, conformità, governance e configurazione. Ogni categoria è un riferimento alle schede nell'interfaccia utente di classificazione BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["Scopri di più sulle API di classificazione BlueXP"].



== 6 giugno 2023 (versione 1.23)



=== Il giapponese è ora supportato durante la ricerca dei nomi dei soggetti dei dati

I nomi giapponesi possono ora essere inseriti quando si cerca il nome di un soggetto in risposta a una richiesta di accesso soggetto a dati (DSAR). È possibile generare un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["Report Data Subject Access Request"] con le informazioni risultanti. È inoltre possibile immettere i nomi giapponesi in https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["Filtro "Data Subject" nella pagina Data Investigation"] identificare i file che contengono il nome dell'oggetto.



=== Ubuntu è ora una distribuzione Linux supportata su cui è possibile installare la classificazione BlueXP

Ubuntu 22.04 è stato qualificato come sistema operativo supportato per la classificazione BlueXP. È possibile installare la classificazione BlueXP su un host Ubuntu Linux nella rete o su un host Linux nel cloud quando si utilizza la versione 1.23 del programma di installazione. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Scopri come installare la classificazione BlueXP su un host con Ubuntu installato"].



=== Red Hat Enterprise Linux 8.6 e 8.7 non sono più supportati con le nuove installazioni di classificazione BlueXP

Queste versioni non sono supportate con le nuove implementazioni perché Red Hat non supporta più Docker, che è un prerequisito. Se si dispone di una macchina di classificazione BlueXP esistente in esecuzione su RHEL 8.6 o 8.7, NetApp continuerà a supportare la configurazione.



=== La classificazione BlueXP può essere configurata come FPolicy Collector per ricevere eventi FPolicy dai sistemi ONTAP

È possibile consentire la raccolta dei registri di controllo dell'accesso ai file nel sistema di classificazione BlueXP per gli eventi di accesso ai file rilevati sui volumi negli ambienti di lavoro. La classificazione BlueXP può acquisire i seguenti tipi di eventi FPolicy e gli utenti che hanno eseguito le azioni sui file: Creare, leggere, scrivere, eliminare, rinominare, Modificare il proprietario/le autorizzazioni e modificare SACL/DACL. https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["Scopri come monitorare e gestire gli eventi di accesso ai file"].



=== Le licenze Data Sense BYOL sono ora supportate nei siti bui

Ora puoi caricare la tua licenza BYOL Data Sense nel portafoglio digitale BlueXP in un sito buio, in modo da ricevere una notifica quando la tua licenza sta per esaurirsi. https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["Scopri come ottenere e caricare la licenza BYOL Data Sense"].



== 3 aprile 2023 (versione 1.22)



=== Nuovo report sulla valutazione del rilevamento dei dati

Il Data Discovery Assessment Report fornisce un'analisi di alto livello dell'ambiente sottoposto a scansione per evidenziare i risultati del sistema e mostrare le aree problematiche e le potenziali fasi di risoluzione dei problemi. L'obiettivo di questo report è aumentare la consapevolezza dei problemi di governance dei dati, delle esposizioni alla sicurezza dei dati e delle lacune nella compliance dei dati del tuo set di dati. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["Scopri come generare e utilizzare il Data Discovery Assessment Report"].



=== Possibilità di implementare la classificazione BlueXP su istanze più piccole nel cloud

Quando si implementa la classificazione BlueXP da un connettore BlueXP in un ambiente AWS, è ora possibile scegliere tra due tipi di istanze più piccoli rispetto a quelli disponibili con l'istanza predefinita. Se si esegue la scansione di un ambiente di piccole dimensioni, questo può contribuire a risparmiare sui costi del cloud. Tuttavia, esistono alcune limitazioni quando si utilizza l'istanza più piccola. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Vedere i tipi di istanze e le limitazioni disponibili"].



=== È ora disponibile uno script standalone per qualificare il sistema Linux prima dell'installazione della classificazione BlueXP

Se si desidera verificare che il sistema Linux soddisfi tutti i prerequisiti indipendentemente dall'esecuzione dell'installazione di classificazione BlueXP, è possibile scaricare uno script separato che esegue solo i prerequisiti. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Scopri come verificare se il tuo host Linux è pronto per installare la classificazione BlueXP"].



== 7 marzo 2023 (versione 1.21)



=== Nuova funzionalità per aggiungere categorie personalizzate dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP consente ora di aggiungere le proprie categorie personalizzate in modo che la classificazione BlueXP identifichi i file che si adattano a tali categorie. La classificazione BlueXP è molto ampia https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["categorie predefinite"], pertanto, questa funzionalità consente di aggiungere categorie personalizzate per identificare dove si trovano informazioni specifiche per l'organizzazione nei dati.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["Scopri di più"^].



=== Ora è possibile aggiungere parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP ha avuto la possibilità di aggiungere parole chiave personalizzate che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare un'interfaccia a riga di comando per aggiungere le parole chiave. In questa release, la possibilità di aggiungere parole chiave personalizzate è nell'interfaccia utente di classificazione di BlueXP, rendendo molto semplice aggiungere e modificare queste parole chiave.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Scopri di più sull'aggiunta di parole chiave personalizzate dall'interfaccia utente di classificazione BlueXP"^].



=== Possibilità di eseguire la classificazione BlueXP *non* dei file di scansione quando verrà modificato l'ultimo tempo di accesso

Per impostazione predefinita, se la classificazione di BlueXP non dispone di permessi di "scrittura" adeguati, il sistema non esegue la scansione dei file nei volumi perché la classificazione di BlueXP non può riportare l'ultimo tempo di accesso alla data e ora originale. Tuttavia, se non si ha alcun problema se l'ultimo tempo di accesso viene ripristinato all'ora originale nei file, è possibile ignorare questo comportamento nella pagina di configurazione in modo che la classificazione BlueXP scansiona i volumi indipendentemente dalle autorizzazioni.

In combinazione con questa funzionalità, è stato aggiunto un nuovo filtro denominato "Scan Analysis Event", che consente di visualizzare i file non classificati perché la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso o i file classificati anche se la classificazione BlueXP non ha potuto ripristinare l'ultimo accesso.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["Scopri di più su "Last Access Time timestamp" e sulle autorizzazioni richieste dalla classificazione BlueXP"].



=== Tre nuovi tipi di dati personali sono identificati dalla classificazione BlueXP

La classificazione BlueXP è in grado di identificare e classificare i file che contengono i seguenti tipi di dati:

* Numero della carta d'identità del Botswana (Omang)
* Numero passaporto Botswana
* Singapore National Registration Identity Card (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].



=== Funzionalità aggiornate per le directory

* L'opzione "Light CSV Report" (Report CSV leggero) per i report di analisi dei dati include ora le informazioni provenienti dalle directory.
* Il filtro dell'ora "ultimo accesso" ora mostra l'ora dell'ultimo accesso per file e directory.




=== Miglioramenti all'installazione

* Il programma di installazione della classificazione BlueXP per i siti senza accesso a Internet (siti oscuri) ora esegue un controllo preliminare per assicurarsi che i requisiti di sistema e di rete siano stati soddisfatti per un'installazione corretta.
* I file di log di audit dell'installazione vengono salvati ora e scritti in `/ops/netapp/install_logs`.




== 5 febbraio 2023 (versione 1.20)



=== Possibilità di inviare e-mail di notifica basate su policy a qualsiasi indirizzo e-mail

Nelle versioni precedenti della classificazione BlueXP, è possibile inviare avvisi e-mail agli utenti BlueXP del proprio account quando alcuni criteri critici restituiscono risultati. Questa funzione ti consente di ricevere notifiche per proteggere i tuoi dati quando non sei online. Ora puoi anche inviare avvisi e-mail dalle policy a qualsiasi altro utente (fino a 20 indirizzi e-mail) che non sia presente nel tuo account BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#send-email-alerts-when-non-compliant-data-is-found["Scopri di più sull'invio di avvisi e-mail in base ai risultati della policy"].



=== Ora è possibile aggiungere modelli personali dall'interfaccia utente di classificazione BlueXP

La classificazione BlueXP ha avuto la possibilità di aggiungere "dati personali" personalizzati che la classificazione BlueXP identificherà per un certo periodo di tempo nelle scansioni future. Tuttavia, era necessario accedere all'host Linux di classificazione BlueXP e utilizzare una riga di comando per aggiungere i modelli personalizzati. In questa release, la possibilità di aggiungere modelli personali utilizzando un regex è nell'interfaccia utente di classificazione BlueXP, rendendo molto semplice aggiungere e modificare questi modelli personalizzati.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Scopri di più sull'aggiunta di modelli personalizzati dall'interfaccia utente di classificazione BlueXP"^].



=== Possibilità di spostare 15 milioni di file utilizzando la classificazione BlueXP

In passato era possibile che la classificazione BlueXP spostasse un massimo di 100,000 file di origine in qualsiasi condivisione NFS. Ora puoi spostare fino a 15 milioni di file alla volta. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#move-source-files-to-an-nfs-share["Scopri di più sullo spostamento dei file di origine utilizzando la classificazione BlueXP"].



=== Possibilità di visualizzare il numero di utenti che hanno accesso ai file di SharePoint Online

Il filtro "numero di utenti con accesso" ora supporta i file memorizzati nei repository SharePoint Online. In passato erano supportati solo i file su condivisioni CIFS. Si noti che i gruppi SharePoint che non sono basati su Active Directory non verranno conteggiati in questo filtro al momento.



=== Il nuovo stato "Partial Success" (operazione riuscita parziale) è stato aggiunto al pannello Action Status (Stato azione)

Il nuovo stato "Partial Success" (successo parziale) indica che un'azione di classificazione BlueXP è terminata e che alcuni elementi hanno avuto esito negativo, ad esempio quando si spostano o si eliminano file 100. Inoltre, lo stato "Finished" (terminato) è stato rinominato "Success" (riuscito). In passato, lo stato "Finished" (terminato) potrebbe elencare le azioni riuscite e non riuscite. Ora lo stato "Success" significa che tutte le azioni sono riuscite su tutti gli elementi. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Vedere come visualizzare il pannello Actions Status (Stato azioni)"].



== 9 gennaio 2023 (versione 1.19)



=== Possibilità di visualizzare un grafico di file che contengono dati sensibili e che sono eccessivamente permissivi

La dashboard di governance ha aggiunto una nuova area _dati sensibili e permessi estesi_ che fornisce una mappa termica dei file che contengono dati sensibili (inclusi dati personali sensibili e sensibili) e che sono eccessivamente permissivi. In questo modo è possibile individuare i rischi associati ai dati sensibili. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Scopri di più"].



=== Nella pagina Data Investigation sono disponibili tre nuovi filtri

Sono disponibili nuovi filtri per perfezionare i risultati visualizzati nella pagina Data Investigation (analisi dati):

* Il filtro "numero di utenti con accesso" mostra i file e le cartelle aperti a un determinato numero di utenti. Puoi scegliere un intervallo di numeri per perfezionare i risultati, ad esempio per vedere quali file sono accessibili da 51-100 utenti.
* I filtri "ora di creazione", "ora di rilevamento", "ultima modifica" e "ultima accesso" consentono ora di creare un intervallo di date personalizzato invece di selezionare semplicemente un intervallo di giorni predefinito. Ad esempio, è possibile cercare i file con un'ora di creazione "più vecchia di 6 mesi" o con una data "ultima modifica" negli ultimi 10 giorni.
* Il filtro "percorso file" consente ora di specificare i percorsi che si desidera escludere dai risultati delle query filtrate. Se si inseriscono percorsi per includere ed escludere determinati dati, la classificazione BlueXP individua prima tutti i file nei percorsi inclusi, quindi rimuove i file dai percorsi esclusi e visualizza i risultati.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-in-the-data-investigation-page["Consulta l'elenco di tutti i filtri che puoi utilizzare per analizzare i tuoi dati"].



=== La classificazione BlueXP può identificare il numero individuale giapponese

La classificazione BlueXP è in grado di identificare e classificare i file che contengono il numero individuale giapponese (noto anche come My Number). Questo include sia il numero personale che il numero personale aziendale. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Scopri tutti i tipi di dati personali che la classificazione BlueXP può identificare nei tuoi dati"].
