= Versione 1,43
:allow-uri-read: 




=== Versione 1,43

Questa versione di classificazione BlueXP  include:

.Assegnare la priorità alle scansioni di classificazione
La classificazione BlueXP  supporta la possibilità di assegnare priorità alle scansioni Map & Classify oltre alle scansioni Mapping-only, consentendo di selezionare le scansioni da completare per prime. La prioritizzazione delle scansioni Map & Classify è supportata durante e prima dell'inizio delle scansioni. Se si sceglie di assegnare la priorità a una scansione mentre è in corso, vengono assegnate priorità sia alla scansione di mappatura che alla scansione di classificazione.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Assegnare priorità alle scansioni"].

.Supporto per categorie di dati canadesi per l'identificazione personale (PII)
Le scansioni di classificazione BlueXP  identificano le categorie di dati PII canadesi. Queste categorie includono informazioni bancarie, numeri di passaporto, numeri di assicurazione sociale, numeri di patente di guida e numeri di carta sanitaria per tutte le province e territori canadesi.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Categorie di dati personali"].

.Classificazione personalizzata (anteprima)
La classificazione BlueXP  supporta classificazioni personalizzate per le scansioni Map & Classify. Grazie alle classificazioni personalizzate, è possibile personalizzare le scansioni BlueXP  per acquisire dati specifici dell'organizzazione utilizzando espressioni regolari. Questa funzione è attualmente in anteprima.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Aggiungere classificazioni personalizzate"].

.Scheda ricerche salvate
La scheda **Policies** è stata rinominata link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Ricerche salvate**"]. La funzionalità rimane invariata.

.Inviare gli eventi di scansione alla timeline BlueXP 
La classificazione BlueXP  supporta l'invio di eventi di classificazione (quando viene avviata e terminata una scansione) a link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Tempistiche di BlueXP "^].

.Aggiornamenti di protezione
* Il pacchetto keras è stato aggiornato, attenuando le vulnerabilità (BDSA-2025-0107 e BDSA-2025-1984).
* La configurazione dei container Docker è stata aggiornata. Il contenitore non ha più accesso alle interfacce di rete dell'host per la creazione di pacchetti di rete grezzi. Riducendo gli accessi non necessari, l'aggiornamento riduce i potenziali rischi di protezione.


.Miglioramenti delle performance
I miglioramenti del codice sono stati implementati per ridurre l'utilizzo della RAM e migliorare le prestazioni complessive della classificazione BlueXP .

.Correzioni dei bug
Sono stati corretti i bug che hanno causato il mancato funzionamento delle scansioni StorageGRID, il mancato caricamento delle opzioni del filtro della pagina di analisi e la valutazione del rilevamento dati per le valutazioni di volumi elevati.
